using Content.Client.Shuttles.Systems;
using Content.Client.Stylesheets;
using Content.Shared._NF.Shuttles.Components;
using Content.Shared._NF.Shipyard.Components;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Systems;
using Content.Shared.Shuttles.UI.MapObjects;
using Content.Shared.Station.Components;
using Content.Shared.Timing;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Audio.Systems;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics.Components;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using System.Numerics;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class MapScreen : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IMapManager _mapManager = default!;
    [Dependency] private readonly IRobustRandom _random = default!;
    private readonly SharedAudioSystem _audio;
    private readonly SharedMapSystem _maps;
    private readonly ShuttleSystem _shuttles;
    private readonly SharedTransformSystem _xformSystem;

    private EntityUid? _console;
    private EntityUid? _shuttleEntity;

    private FTLState _state;
    private StartEndTime _ftlTime;
    private bool _inCombat;

    private List<ShuttleBeaconObject> _beacons = new();
    private List<ShuttleExclusionObject> _exclusions = new();

    private TimeSpan _nextPing;
    private TimeSpan _pingCooldown = TimeSpan.FromSeconds(3);
    private TimeSpan _nextMapDequeue;

    private float _minMapDequeue = 0.001f; // Frontier: 0.05<0.001
    private float _maxMapDequeue = 0.005f; // Frontier: 0.25<0.005

    private TimeSpan _nextAutoRefresh; // Lua
    private readonly TimeSpan _autoRefreshInterval = TimeSpan.FromMinutes(1); // Lua
    private readonly Font _mapObjectFont;

    private bool _settingTargeting;

    public event Action<MapCoordinates, Angle>? RequestFTL;
    public event Action<NetEntity, Angle>? RequestBeaconFTL;
    public event Action<NetEntity?, NetEntity>? RequestTrackEntity; // Frontier
    public event Action<MapCoordinates>? RequestTargetMark; // Lua

    private readonly Dictionary<MapId, BoxContainer> _mapHeadings = new();
    private readonly Dictionary<MapId, List<IMapObject>> _mapObjects = new();
    private readonly List<(MapId mapId, IMapObject mapobj)> _pendingMapObjects = new();

    /// <summary>
    /// Store the names of map object controls for re-sorting later.
    /// </summary>
    private Dictionary<Control, MapObjectSortKey> _mapObjectControls = new();

    private readonly record struct MapObjectSortKey(int Group, string Name);

    private List<Control> _sortChildren = new();

    public MapScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _audio = _entManager.System<SharedAudioSystem>();
        _maps = _entManager.System<SharedMapSystem>();
        _shuttles = _entManager.System<ShuttleSystem>();
        _xformSystem = _entManager.System<SharedTransformSystem>();
        _mapObjectFont = new VectorFont(IoCManager.Resolve<IResourceCache>().GetResource<FontResource>("/Fonts/NotoSans/NotoSans-Regular.ttf"), 9);

        MapRebuildButton.OnPressed += MapRebuildPressed;

        OnVisibilityChanged += OnVisChange;

        MapFTLButton.OnToggled += FtlPreviewToggled;
        MapMarkButton.OnToggled += obj => MapRadar.MarkMode = obj.Pressed; // Lua
        MapRadar.MarkPlaced += coords => // Lua
        {
            RequestTargetMark?.Invoke(coords);
            MapMarkButton.Pressed = false;
            MapRadar.MarkMode = false;
        };
        MapZoomSlider.OnValueChanged += range => SetMapZoom(range.Value);
        MapRadar.WorldRangeChanged += _ => UpdateMapZoomDisplay();
        UpdateMapZoomDisplay();
        ApplyCompactMapStyle(RightDisplayMap);

        // Just pass it on up.
        MapRadar.RequestFTL += (coords, angle) =>
        {
            RequestFTL?.Invoke(coords, angle);
        };

        MapRadar.RequestBeaconFTL += (ent, angle) =>
        {
            RequestBeaconFTL?.Invoke(ent, angle);
        };

        _nextAutoRefresh = _timing.CurTime; // Lua
    }

    public void UpdateState(ShuttleMapInterfaceState state)
    {
        // Only network the accumulator due to ping making the thing fonky.
        // This should work better with predicting network states as they come in.
        _beacons = state.Destinations;
        _exclusions = state.Exclusions;
        var previousState = _state;
        var wasBlocked = IsFTLBlocked();
        _state = state.FTLState;
        _ftlTime = state.FTLTime;
        MapRadar.InFtl = true;
        MapFTLState.Text = Loc.GetString($"shuttle-console-ftl-state-{_state.ToString()}");

        //frontier - we only allow pre-approved vessels to FTL
        if (!_entManager.HasComponent<ShuttleFTLComponent>(_shuttleEntity))
        {
            MapFTLButton.Visible = true; //false отключит БСС
        }
        else
        {
            MapFTLButton.Visible = true;
        }

        switch (_state)
        {
            case FTLState.Available:
                SetFTLAllowed(true);
                FTLBar.SetColor(Color.FromHex("#80C71F"));
                MapRadar.InFtl = false;
                break;
            case FTLState.Starting:
                SetFTLAllowed(false);
                FTLBar.SetColor(Color.FromHex("#169C9C"));
                break;
            case FTLState.Travelling:
                SetFTLAllowed(false);
                FTLBar.SetColor(Color.FromHex("#8932B8"));
                break;
            case FTLState.Arriving:
                SetFTLAllowed(false);
                FTLBar.SetColor(Color.FromHex("#F9801D"));
                break;
            case FTLState.Cooldown:
                SetFTLAllowed(false);
                if (_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform)
                    && shuttleXform.MapID != MapId.Nullspace)
                {
                    var mapId = shuttleXform.MapID;
                    var targetOffset = _maps.GetGridPosition(_shuttleEntity.Value);
                    var mapChanged = MapRadar.ViewingMap != mapId;
                    if (mapChanged || previousState != FTLState.Cooldown)
                        MapRadar.SetMap(mapId, targetOffset, recentering: true);
                }

                FTLBar.SetColor(Color.FromHex("#B02E26"));
                MapRadar.InFtl = false;
                break;
            // Fallback in case no FTL state or the likes.
            default:
                SetFTLAllowed(false);
                FTLBar.SetColor(Color.FromHex("#B02E26"));
                MapRadar.InFtl = false;
                break;
        }

        if (IsFTLBlocked())
        {
            MapRebuildButton.Disabled = true;
            ClearMapObjects();
        }
        else if (wasBlocked)
        {
            // FTL just finished (or became available) - refresh the destination list immediately
            // instead of waiting for the next auto-refresh tick.
            RebuildMapObjects();
            _nextAutoRefresh = _timing.CurTime + _autoRefreshInterval;
        }
    }

    private void SetFTLAllowed(bool value)
    {
        if (value && !_inCombat)
        {
            MapFTLButton.Disabled = false;
            MapMarkButton.Disabled = false;
        }
        else
        {
            MapFTLButton.Pressed = false;
            MapRadar.FtlMode = false;
            MapRadar.ShowFTLRangeOnly = false;
            MapFTLButton.Disabled = true;

            MapMarkButton.Pressed = false;
            MapRadar.MarkMode = false;
            MapMarkButton.Disabled = true;
        }
    }

    private void FtlPreviewToggled(BaseButton.ButtonToggledEventArgs obj)
    {
        SetTargeting(obj.Pressed);
    }

    private void SetTargeting(bool pressed)
    {
        if (_settingTargeting)
            return;

        _settingTargeting = true;
        try
        {
            if (pressed)
            {
                MapRadar.FtlMode = true;
                MapRadar.ShowFTLRangeOnly = false;
                MapRadar.ShowFTLRange = true;
                MapRadar.NoFTLRange = false;
                MapFTLButton.Pressed = true;

                MapMarkButton.Pressed = false;
                MapRadar.MarkMode = false;
                MapMarkButton.Disabled = true;
            }
            else
            {
                MapRadar.FtlMode = false;
                MapRadar.ShowFTLRange = true;
                MapRadar.NoFTLRange = false;
                MapFTLButton.Pressed = false;

                if (!IsFTLBlocked())
                    MapMarkButton.Disabled = false;
            }
        }
        finally
        {
            _settingTargeting = false;
        }
    }

    public void SetConsole(EntityUid? console)
    {
        _console = console;
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;
        MapRadar.SetShuttle(shuttle);
    }

    private void OnVisChange(Control obj)
    {
        if (!obj.Visible)
            return;

        // Centre map screen to the shuttle.
        if (_shuttleEntity != null)
        {
            var mapPos = _xformSystem.GetMapCoordinates(_shuttleEntity.Value);
            MapRadar.SetMap(mapPos.MapId, mapPos.Position);
        }
    }

    /// <summary>
    /// Does a sonar-like effect on the map.
    /// </summary>
    public void PingMap()
    {
        if (_console != null)
        {
            _audio.PlayEntity(new SoundPathSpecifier("/Audio/Effects/Shuttle/radar_ping.ogg"), Filter.Local(), _console.Value, true);
        }

        RebuildMapObjects();

        _nextPing = _timing.CurTime + _pingCooldown;
        MapRebuildButton.Disabled = true;
    }

    private void BumpMapDequeue()
    {
        _nextMapDequeue = _timing.CurTime + TimeSpan.FromSeconds(_random.NextFloat(_minMapDequeue, _maxMapDequeue));
    }

    private void MapRebuildPressed(BaseButton.ButtonEventArgs obj)
    {
        PingMap();
        // Show FTL range circle without targeting elements
        MapRadar.ShowFTLRangeOnly = true;
    }

    private void SetMapZoom(float zoom)
    {
        MapRadar.SetRadarZoom(zoom);
        UpdateMapZoomDisplay();
    }

    private void UpdateMapZoomDisplay()
    {
        var zoom = MapRadar.RadarZoom;
        MapZoomSlider.SetValueWithoutEvent(zoom);
    }

    private static void ApplyCompactMapStyle(Control root)
    {
        foreach (var child in root.Children)
        {
            switch (child)
            {
                case Label label:
                    label.AddStyleClass(StyleNano.StyleClassLabelSmall);
                    break;
            }

            ApplyCompactMapStyle(child);
        }
    }

    /// <summary>
    /// Clears all sector objects across all maps (e.g. if we start FTLing or need to re-ping).
    /// </summary>
    private void ClearMapObjects()
    {
        _mapObjectControls.Clear();
        HyperspaceDestinations.DisposeAllChildren();
        _pendingMapObjects.Clear();
        _mapObjects.Clear();
        _mapHeadings.Clear();
    }

    /// <summary>
    /// Gets all map objects at time of ping and adds them to pending to be added over time.
    /// </summary>
    private void RebuildMapObjects()
    {
        ClearMapObjects();

        if (_shuttleEntity == null)
            return;

        var mapComps = _entManager.AllEntityQueryEnumerator<MapComponent, TransformComponent, MetaDataComponent>();
        MapId ourMap = MapId.Nullspace;

        if (_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform))
        {
            ourMap = shuttleXform.MapID;
        }

        while (mapComps.MoveNext(out var mapUid, out var mapComp, out var mapXform, out var mapMetadata))
        {
            if (_console != null && !_shuttles.CanFTLTo(_shuttleEntity.Value, mapComp.MapId, _console.Value))
            { continue; }
            var mapName = mapMetadata.EntityName;

            if (string.IsNullOrEmpty(mapName))
            {
                mapName = Loc.GetString("shuttle-console-unknown");
            }

            var heading = new CollapsibleHeading(mapName);

            heading.MinHeight = 28f;
            heading.AddStyleClass(ContainerButton.StyleClassButton);
            heading.HorizontalAlignment = HAlignment.Stretch;
            heading.Label.HorizontalAlignment = HAlignment.Center;
            heading.Label.HorizontalExpand = true;
            heading.Label.FontColorOverride = Color.FromHex("#C5CEDB");
            heading.Label.FontOverride = _mapObjectFont;
            heading.Label.AddStyleClass(StyleNano.StyleClassLabelSmall);
            heading.HorizontalExpand = true;

            var gridContents = new BoxContainer()
            {
                Orientation = LayoutOrientation.Vertical,
                VerticalExpand = true,
                SeparationOverride = 3,
            };

            var body = new CollapsibleBody()
            {
                HorizontalAlignment = HAlignment.Stretch,
                VerticalAlignment = VAlignment.Top,
                HorizontalExpand = true,
                Children =
                {
                    gridContents
                }
            };

            var mapButton = new Collapsible(heading, body);

            heading.OnToggled += args =>
            {
                if (args.Pressed)
                {
                    HideOtherCollapsibles(mapButton);
                }
            };

            _mapHeadings.Add(mapComp.MapId, gridContents);
            foreach (var grid in _mapManager.GetAllGrids(mapComp.MapId))
            {
                _entManager.TryGetComponent(grid.Owner, out IFFComponent? iffComp);

                // Frontier: Service flags for shuttles
                // If it is a GridMapObject, Turn the mapObj.ServiceFlags into a string like Food = F, Medical = M, etc.
                // This should turn the ServiceFlags into a string like "FM" for Food and Medical.
                var serviceFlagsText = string.Empty;
                if (iffComp?.ServiceFlags != null)
                {
                    serviceFlagsText = _shuttles.GetServiceFlagsSuffix(iffComp.ServiceFlags);
                }

                var flags = iffComp?.Flags ?? IFFFlags.None;
                var hideLabelShuttle = false;
                var gridObj = new GridMapObject()
                {
                    Name = _entManager.GetComponent<MetaDataComponent>(grid.Owner).EntityName + serviceFlagsText,
                    // Frontier: Service Flags
                    ServiceFlags = iffComp?.ServiceFlags ?? ServiceFlags.None,
                    Entity = grid.Owner,
                    HideButton = (flags & IFFFlags.HideLabel) != 0x0 || hideLabelShuttle,
                };

                // Always show our shuttle immediately
                if (grid.Owner == _shuttleEntity)
                {
                    AddMapObject(mapComp.MapId, gridObj);
                }

                // If we can show it then add it to pending.
                else if (
                    !_shuttles.IsBeaconMap(mapUid) &&
                    _shuttles.CanDraw(grid.Owner, iffComp: iffComp) &&
                    (iffComp == null ||
                     ((flags & IFFFlags.Hide) == 0x0 &&
                      (flags & IFFFlags.HideLabel) == 0x0 &&
                      !hideLabelShuttle)) && // Lua decrypt mod + Lua alliesOnRadar
                    !gridObj.HideButton)
                {
                    _pendingMapObjects.Add((mapComp.MapId, gridObj));
                }
            }

            foreach (var (beacon, _) in _shuttles.GetExclusions(mapComp.MapId, _exclusions))
            {
                if (beacon.HideButton)
                    continue;

                _pendingMapObjects.Add((mapComp.MapId, beacon));
            }

            foreach (var (beacon, _) in _shuttles.GetBeacons(mapComp.MapId, _beacons))
            {
                if (beacon.HideButton)
                    continue;

                _pendingMapObjects.Add((mapComp.MapId, beacon));
            }

            HyperspaceDestinations.AddChild(mapButton);

            // Zoom in to our map
            if (mapComp.MapId == MapRadar.ViewingMap)
            {
                mapButton.BodyVisible = true;
            }
        }

        _pendingMapObjects.Sort((x, y) =>
        {
            var xKey = GetMapObjectSortKey(x.mapobj);
            var yKey = GetMapObjectSortKey(y.mapobj);
            return CompareMapObjectSortKeys(xKey, yKey);
        });

        foreach (var mapObj in _pendingMapObjects) // Lua
        {
            AddMapObject(mapObj.mapId, mapObj.mapobj); // Lua
        }
        _pendingMapObjects.Clear(); // Lua
    }

    /// <summary>
    /// Hides other maps upon the specified collapsible being selected (AKA hacky collapsible groups).
    /// </summary>
    private void HideOtherCollapsibles(Collapsible collapsible)
    {
        foreach (var child in HyperspaceDestinations.Children)
        {
            if (child is not Collapsible childCollapse || childCollapse == collapsible)
                continue;

            childCollapse.BodyVisible = false;
        }
    }

    /// <summary>
    /// Returns true if we shouldn't be able to select the FTL button.
    /// </summary>
    private bool IsFTLBlocked()
    {
        switch (_state)
        {
            case FTLState.Available:
                return false;
            case FTLState.Cooldown:
                return false;
            default:
                return true;
        }
    }

    private void OnMapObjectPress(IMapObject mapObject)
    {
        if (IsFTLBlocked())
            return;

        var coordinates = _shuttles.GetMapCoordinates(mapObject);

        // If it's our map then scroll, otherwise just set position there.
        MapRadar.SetMap(coordinates.MapId, coordinates.Position, recentering: true);
    }

    // Frontier: entity tracking
    private void OnMapObjectTrackPress(IMapObject mapObject)
    {
        if (mapObject is not GridMapObject gridObj)
            return;

        RequestTrackEntity?.Invoke(_shuttleEntity is null ? null : _entManager.GetNetEntity(_shuttleEntity), _entManager.GetNetEntity(gridObj.Entity));
    }
    // End Frontier: entity tracking

    public void SetMap(MapId mapId, Vector2 position)
    {
        MapRadar.SetMap(mapId, position);
        MapRadar.Offset = position;
    }

    /// <summary>
    /// Adds a map object to the specified sector map.
    /// </summary>
    private void AddMapObject(MapId mapId, IMapObject mapObj)
    {
        var existing = _mapObjects.GetOrNew(mapId);
        existing.Add(mapObj);

        var gridContents = _mapHeadings[mapId];

        var gridButton = new Button()
        {
            Text = mapObj.Name,
            HorizontalExpand = true,
            MinHeight = 18f,
        };
        gridButton.AddStyleClass("ButtonSquare");

        gridButton.Label.ClipText = true; // Frontier
        gridButton.Label.FontColorOverride = Color.FromHex("#C5CEDB");
        gridButton.Label.FontOverride = _mapObjectFont;

        var iconControl = CreateMapObjectIcon(mapObj);

        var iconSlot = new CenterContainer()
        {
            MinWidth = 16f,
            MaxWidth = 16f,
            MinHeight = 18f,
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Center,
            Children =
            {
                iconControl
            }
        };

        var gridContainer = new BoxContainer()
        {
            SeparationOverride = 4,
            Children =
            {
                iconSlot,
                gridButton
            }
        };

        _mapObjectControls.Add(gridContainer, GetMapObjectSortKey(mapObj));
        gridContents.AddChild(gridContainer);

        gridButton.OnPressed += args =>
        {
            OnMapObjectPress(mapObj);
        };

        // Frontier: tracking button handler
        if (mapObj is GridMapObject gridObj)
        {
            var trackButton = new Button()
            {
                ToolTip = Loc.GetString("shuttle-console-map-track"),
                MinWidth = 32,
                MaxWidth = 32,
                MinHeight = 18f,
            };
            trackButton.AddStyleClass("ButtonSquare");
            trackButton.AddChild(new MapTargetIconControl());
            trackButton.OnPressed += args =>
            {
                OnMapObjectTrackPress(mapObj);
            };
            gridContainer.Children.Add(trackButton);
        }
        // End Frontier: tracking button handler

        if (gridContents.ChildCount > 1)
        {
            // Re-sort the children
            _sortChildren.Clear();

            foreach (var child in gridContents.Children)
            {
                DebugTools.Assert(_mapObjectControls.ContainsKey(child));
                _sortChildren.Add(child);
            }

            foreach (var child in _sortChildren)
            {
                child.Orphan();
            }

            _sortChildren.Sort((x, y) =>
            {
                var xKey = _mapObjectControls[x];
                var yKey = _mapObjectControls[y];

                return CompareMapObjectSortKeys(xKey, yKey);
            });

            foreach (var control in _sortChildren)
            {
                gridContents.AddChild(control);
            }
        }
    }

    private MapObjectSortKey GetMapObjectSortKey(IMapObject mapObj)
    {
        var group = mapObj switch
        {
            GridMapObject grid when grid.Entity == _shuttleEntity => 0,
            GridMapObject grid when IsStationMapObject(grid) => 1,
            GridMapObject grid when _entManager.HasComponent<ShuttleDeedComponent>(grid.Entity) => 2,
            GridMapObject => 3,
            ShuttleBeaconObject => 5,
            ShuttleExclusionObject => 6,
            _ => 7,
        };

        return new MapObjectSortKey(group, mapObj.Name);
    }

    private static int CompareMapObjectSortKeys(MapObjectSortKey x, MapObjectSortKey y)
    {
        var groupCompare = x.Group.CompareTo(y.Group);
        if (groupCompare != 0)
            return groupCompare;

        return string.Compare(x.Name, y.Name, StringComparison.CurrentCultureIgnoreCase);
    }

    private Control CreateMapObjectIcon(IMapObject mapObj)
    {
        if (mapObj is ShuttleBeaconObject)
            return new MapObjectIconControl(MapObjectIconShape.Diamond, Color.FromHex("#7DDBA3"), false);
        if (mapObj is ShuttleExclusionObject)
            return new MapObjectIconControl(MapObjectIconShape.Diamond, Color.FromHex("#E07070"), false);
        if (mapObj is GridMapObject grid)
        {
            if (IsStationMapObject(grid))
                return new MapObjectIconControl(MapObjectIconShape.Hexagon, Color.FromHex("#5EC8E8"), true);

            return new MapObjectIconControl(MapObjectIconShape.Triangle, Color.FromHex("#F0C674"), true);
        }

        return new MapObjectIconControl(MapObjectIconShape.Hexagon, Color.FromHex("#8A96A8"), false);
    }

    private bool IsStationMapObject(GridMapObject grid)
    {
        return _entManager.HasComponent<StationMemberComponent>(grid.Entity);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var curTime = _timing.CurTime;

        if (!IsFTLBlocked() && _nextAutoRefresh <= curTime) // Lua
        {
            RebuildMapObjects(); // Lua
            _nextAutoRefresh = curTime + _autoRefreshInterval; // Lua
        }

        MapRebuildButton.Disabled = IsFTLBlocked() || _nextPing > curTime;

        var progress = _ftlTime.ProgressAt(curTime);
        FTLBar.SetProgress(float.IsFinite(progress) ? progress : 1);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        MapRadar.SetMapObjects(_mapObjects);
        base.Draw(handle);
    }

    public void Startup()
    {
        if (_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform))
        {
            SetMap(shuttleXform.MapID, _maps.GetGridPosition((_shuttleEntity.Value, null, shuttleXform)));
        }
    }

    private enum MapObjectIconShape
    {
        Triangle,
        Pentagon,
        Hexagon,
        Diamond,
    }

    private sealed class MapObjectIconControl : Control
    {
        private readonly MapObjectIconShape _shape;
        private readonly Color _color;
        private readonly bool _filled;

        public MapObjectIconControl(MapObjectIconShape shape, Color color, bool filled)
        {
            _shape = shape;
            _color = color;
            _filled = filled;
            MinSize = new Vector2(12f, 12f);
            MaxSize = new Vector2(12f, 12f);
            HorizontalAlignment = HAlignment.Center;
            VerticalAlignment = VAlignment.Center;
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);

            var center = new Vector2(PixelWidth * 0.5f, PixelHeight * 0.5f);
            var radius = MathF.Min(PixelWidth, PixelHeight) * 0.46f;
            var sides = _shape switch
            {
                MapObjectIconShape.Triangle => 3,
                MapObjectIconShape.Pentagon => 5,
                MapObjectIconShape.Hexagon => 6,
                MapObjectIconShape.Diamond => 4,
                _ => 4,
            };
            const float angleOffset = -MathF.PI / 2f;
            var vertices = new Vector2[sides];

            for (var i = 0; i < sides; i++)
            {
                var angle = angleOffset + MathF.Tau * i / sides;
                vertices[i] = center + new Vector2(MathF.Cos(angle), MathF.Sin(angle)) * radius;
            }

            handle.DrawPrimitives(
                _filled ? DrawPrimitiveTopology.TriangleFan : DrawPrimitiveTopology.LineLoop,
                vertices,
                _color);
        }
    }

    private sealed class MapTargetIconControl : Control
    {
        public MapTargetIconControl()
        {
            MinSize = new Vector2(14f, 14f);
            MaxSize = new Vector2(14f, 14f);
            HorizontalAlignment = HAlignment.Center;
            VerticalAlignment = VAlignment.Center;
            MouseFilter = MouseFilterMode.Ignore;
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);

            var center = new Vector2(PixelWidth * 0.5f, PixelHeight * 0.5f);
            var color = Color.FromHex("#C5CEDB");
            const float radius = 3.5f;
            const float outer = 6f;

            handle.DrawCircle(center, radius, color, false);
            handle.DrawCircle(center, 1f, color, true);
            handle.DrawLine(center + new Vector2(0f, -outer), center + new Vector2(0f, -radius - 1f), color);
            handle.DrawLine(center + new Vector2(0f, radius + 1f), center + new Vector2(0f, outer), color);
            handle.DrawLine(center + new Vector2(-outer, 0f), center + new Vector2(-radius - 1f, 0f), color);
            handle.DrawLine(center + new Vector2(radius + 1f, 0f), center + new Vector2(outer, 0f), color);
        }
    }
}
