using Content.Client._Mono.Radar;
using Content.Client.Shuttles.Systems;
using Content.Client.Station; // Frontier
using Content.Shared._Crescent.ShipShields;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Systems;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Localization;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics;
using Robust.Shared.Physics.Collision.Shapes;
using Robust.Shared.Physics.Components;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
[Virtual]
public partial class ShuttleNavControl : BaseShuttleControl // Mono
{
    [Dependency] private readonly IMapManager _mapManager = default!;
    [Dependency] private readonly IUserInterfaceManager _uiManager = default!;
    protected override bool AllowResize => true; // Lua
    protected override bool ScaleWithControlSize => true; // Lua
    private readonly SharedShuttleSystem _shuttles;
    private readonly SharedTransformSystem _transform;

    /// <summary>
    /// Used to transform all of the radar objects. Typically is a shuttle console parented to a grid.
    /// </summary>
    protected EntityCoordinates? _coordinates; // Mono

    /// <summary>
    /// Entity of controlling console
    /// </summary>
    private EntityUid? _consoleEntity;

    protected Angle? _rotation; // Mono

    private Dictionary<NetEntity, List<DockingPortState>> _docks = new();

    public bool ShowIFF { get; set; } = true;
    public bool ShowIFFShuttles { get; set; } = true;
    public bool ShowDocks { get; set; } = true;
    public bool RotateWithEntity { get; set; } = true;

    /// <summary>
    /// Lua: the dock port to highlight on the radar, if any.
    /// </summary>
    public NetEntity? HighlightDockPort { get; set; }

    #region Mono
    // doesn't support absolute panning and angle follow, but why would you need that?
    protected bool _relativePanning = false;
    protected bool _angleFollow = true;
    private bool _radarModeDefaultsApplied;
    private bool _wasPanned = false;

    private enum RadarAzimuthMode : byte
    {
        Edge,
        Ring,
        Off,
    }

    private BoxContainer? _radarModeButtons;
    private RadarModeButton? _radarAzimuthButton;
    private RadarAzimuthMode _azimuthMode;
    #endregion

    /// <summary>
    ///   If present, called for every IFF. Must determine if it should or should not be shown.
    /// </summary>
    public Func<EntityUid, MapGridComponent, IFFComponent?, string?, bool>? IFFFilter { get; set; } = null;

    /// <summary>
    /// Raised if the user left-clicks on the radar control with the relevant entitycoordinates.
    /// </summary>
    public Action<EntityCoordinates>? OnRadarClick;

    private List<Entity<MapGridComponent>> _grids = new();
    public ShuttleNavControl() : this(64f, 256f, 256f) { } // Mono

    public ShuttleNavControl(float minRange, float maxRange, float range) : base(minRange, maxRange, range) // Mono
    {
        RobustXamlLoader.Load(this);
        _shuttles = EntManager.System<SharedShuttleSystem>();
        _transform = EntManager.System<SharedTransformSystem>();
        _station = EntManager.System<StationSystem>(); // Frontier
        _blips = EntManager.System<RadarBlipsSystem>();

        OnMouseEntered += HandleMouseEntered;
        OnMouseExited += HandleMouseExited;
    }

    private double _pruneAccumSeconds;
    protected virtual void ModifyGridPalette(ref Color fillColor, ref Color edgeColor, ref float fillAlpha, EntityUid gridUid, bool self) { } // Lua
    protected virtual bool ShowRadarPositionMarker => true; // Lua
    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        if (_wasPanned) // Mono hack
            return;

        _coordinates = coordinates;
        // Seed rotation once; Draw drives it via _angleFollow afterwards.
        _rotation ??= angle ?? Angle.Zero;
    }

    public void SetConsole(EntityUid? consoleEntity)
    {
        if (_consoleEntity == consoleEntity)
            return;

        _consoleEntity = consoleEntity;
        _radarModeDefaultsApplied = false;
        ApplyRadarModeDefaults();
    }

    private void EnsureRadarModeButtons()
    {
        if (_radarModeButtons != null)
            return;

        if (Parent is not LayoutContainer parent)
            return;

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        _radarModeButtons = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 2,
            HorizontalExpand = false,
            VerticalExpand = false,
            MouseFilter = MouseFilterMode.Stop,
        };

        _radarAzimuthButton = CreateRadarModeButton(RadarModeButtonIcon.Azimuth);
        _radarAzimuthButton.ToolTip = Loc.GetString("shuttle-console-button-azimuth");
        _radarAzimuthButton.OnPressed += _ =>
        {
            _azimuthMode = _azimuthMode switch
            {
                RadarAzimuthMode.Edge => RadarAzimuthMode.Ring,
                RadarAzimuthMode.Ring => RadarAzimuthMode.Off,
                _ => RadarAzimuthMode.Edge,
            };
        };

        _radarModeButtons.AddChild(_radarAzimuthButton);

        parent.AddChild(_radarModeButtons);
        LayoutContainer.SetAnchorAndMarginPreset(_radarModeButtons, LayoutContainer.LayoutPreset.BottomLeft, margin: 10);
    }

    private void ApplyRadarModeDefaults()
    {
        if (_radarModeDefaultsApplied)
            return;

        if (!EntManager.TryGetComponent<RadarConsoleComponent>(_consoleEntity, out var radar))
            return;

        // Lua: RadarConsoleComponent has no Pannable/NoRotate/RelativePanning fields here; keep prior defaults.
        _radarModeDefaultsApplied = true;
    }

    private static RadarModeButton CreateRadarModeButton(RadarModeButtonIcon icon = RadarModeButtonIcon.None)
    {
        return new RadarModeButton(icon)
        {
            MinWidth = 16f,
            MaxWidth = 16f,
            MinHeight = 16f,
            MaxHeight = 16f,
            HorizontalExpand = false,
            VerticalExpand = false,
            ModulateSelfOverride = Color.White.WithAlpha(0.55f),
        };
    }

    internal enum RadarModeButtonIcon : byte
    {
        None,
        Azimuth,
        Rotation,
        Anchor,
        Reset
    }

    public sealed class RadarModeButton : BaseButton
    {
        private readonly RadarModeButtonIcon _icon;

        internal RadarModeButton(RadarModeButtonIcon icon)
        {
            _icon = icon;
        }

        protected override Vector2 MeasureOverride(Vector2 availableSize)
        {
            return new Vector2(16f, 16f);
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            var alpha = DrawMode switch
            {
                DrawModeEnum.Pressed => 0.62f,
                DrawModeEnum.Hover => 0.48f,
                _ => 0.32f,
            };

            var center = new Vector2(PixelSize.X * 0.5f, PixelSize.Y * 0.5f);
            var radius = MathF.Min(PixelSize.X, PixelSize.Y) * 0.42f;
            handle.DrawCircle(center, radius, Color.White.WithAlpha(alpha));

            var up = new Vector2(0f, -radius);
            var down = new Vector2(0f, radius);
            var leftOffs = new Vector2(-radius, 0f);
            var rightOffs = new Vector2(radius, 0f);
            var top = center + up;
            var bottom = center + down;
            var left = center + leftOffs;
            var right = center + rightOffs;

            switch (_icon) {
                case RadarModeButtonIcon.Azimuth:
                {
                    var iconColor = Color.Black.WithAlpha(0.95f);
                    var topLeft = center + (up + leftOffs) / MathF.Sqrt(2f);
                    var topRight = center + (up + rightOffs) / MathF.Sqrt(2f);
                    var bottomLeft = center + (down + leftOffs) / MathF.Sqrt(2f);
                    var bottomRight = center + (down + rightOffs) / MathF.Sqrt(2f);

                    handle.DrawLine(topLeft, bottomRight, iconColor);
                    handle.DrawLine(bottomLeft, topRight, iconColor);
                    handle.DrawLine(left, right, iconColor);
                    handle.DrawLine(bottom, top, iconColor);
                    break;
                }
                case RadarModeButtonIcon.Rotation:
                {
                    var iconColor = Color.Yellow.WithAlpha(0.95f);
                    var innerRatio = 0.8f;
                    var segCount = 3;
                    var prevOffs = up * innerRatio;
                    for (var i = 0; i < segCount; i++)
                    {
                        var angle = Angle.FromDegrees(120f * i / (float)segCount - 15f);
                        var thisOffs = angle.RotateVec(up * innerRatio);
                        var thisPointUp = center + thisOffs;
                        var thisPointDown = center - thisOffs;
                        var oldPointUp = center + prevOffs;
                        var oldPointDown = center - prevOffs;
                        handle.DrawLine(oldPointUp, thisPointUp, iconColor);
                        handle.DrawLine(oldPointDown, thisPointDown, iconColor);
                        prevOffs = thisOffs;
                    }
                    break;
                }
                case RadarModeButtonIcon.Anchor:
                {
                    var iconColor = Color.Blue.WithAlpha(0.95f);
                    var stemTop = center + up * 0.5f;
                    var crossLeft = center + leftOffs * 0.3f + up * 0.7f;
                    var crossRight = center + rightOffs * 0.3f + up * 0.7f;
                    var leftFluke = center + leftOffs * 0.6f + down * 0.6f;
                    var rightFluke = center + rightOffs * 0.6f + down * 0.6f;
                    var innerRadius = radius * 0.4f;
                    var innerTop = center + up * 0.6f;

                    handle.DrawCircle(innerTop, innerRadius, iconColor, false);
                    handle.DrawLine(stemTop, bottom, iconColor);
                    handle.DrawLine(crossLeft, crossRight, iconColor);
                    handle.DrawLine(bottom, leftFluke, iconColor);
                    handle.DrawLine(bottom, rightFluke, iconColor);
                    break;
                }
                case RadarModeButtonIcon.Reset:
                {
                    var iconColor = Color.Red.WithAlpha(0.95f);
                    handle.DrawLine(left, right, iconColor);
                    break;
                }
                default:
                    break;
            }
        }
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        // Frontier: Clicking coordinates
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _isMouseDown = false;

        if (_coordinates == null || _rotation == null || OnRadarClick == null)
            return;
        // End Frontier

        OnRadarClick?.Invoke(GetMouseEntityCoordinates(args.RelativePosition));
    }

    /// <summary>
    /// Gets the entity coordinates of where the mouse position is, relative to the control.
    /// </summary>
    [PublicAPI]
    public EntityCoordinates GetMouseCoordinatesFromCenter()
    {
        if (_coordinates == null || _rotation == null)
        {
            return EntityCoordinates.Invalid;
        }

        var pos = _uiManager.MousePositionScaled.Position - GlobalPosition;
        return GetMouseEntityCoordinates(pos);
    }

    private Vector2 GetScaledMouseUiPosition()
    {
        return (_uiManager.MousePositionScaled.Position - GlobalPosition) * UIScale;
    }

    public void UpdateState(NavInterfaceState state)
    {
        EnsureRadarModeButtons();
        ApplyRadarModeDefaults();
        SetMatrix(EntManager.GetCoordinates(state.Coordinates), state.Angle);

        WorldMaxRange = state.MaxRange;

        if (WorldMaxRange < WorldRange)
        {
            ActualRadarRange = WorldMaxRange;
        }

        if (WorldMaxRange < WorldMinRange)
            WorldMinRange = WorldMaxRange;

        ActualRadarRange = Math.Clamp(ActualRadarRange, WorldMinRange, WorldMaxRange);

        RotateWithEntity = state.RotateWithEntity;

        _docks = state.Docks;

        NFUpdateState(state); // Frontier Update State
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        //UseCircleMaskShader(handle); // Mono use, Lua no use

        base.Draw(handle);
        _pruneAccumSeconds += Timing.FrameTime.TotalSeconds;
        if (_pruneAccumSeconds >= 5.0)
        {
            _pruneAccumSeconds = 0;
            var toRemove = new List<EntityUid>();
            foreach (var kvp in GridData)
            { if (!EntManager.EntityExists(kvp.Key)) toRemove.Add(kvp.Key); }
            foreach (var uid in toRemove) GridData.Remove(uid);
        }

        DrawBacking(handle);
        DrawCircles(handle);

        // No data
        if (_coordinates == null || _rotation == null)
        {
            return;
        }

        var xformQuery = EntManager.GetEntityQuery<TransformComponent>();
        var fixturesQuery = EntManager.GetEntityQuery<FixturesComponent>();
        var bodyQuery = EntManager.GetEntityQuery<PhysicsComponent>();

        if (!xformQuery.TryGetComponent(_coordinates.Value.EntityId, out var xform)
            || xform.MapID == MapId.Nullspace)
        {
            return;
        }

        var coordEnt = _coordinates.Value.EntityId;
        var coordEntRot = _transform.GetWorldRotation(coordEnt);
        if (_angleFollow && EntManager.TryGetComponent<TransformComponent>(coordEnt, out _))
            _rotation = coordEntRot;
        else
            _rotation = Angle.Zero;

        var worldRot = _rotation.Value;
        var mapPos = _transform.ToMapCoordinates(_coordinates.Value).Offset(_rotation.Value.RotateVec(Offset));
        var mapCoord = _transform.ToCoordinates(mapPos);
        var worldToShuttle = Matrix3Helpers.CreateTranslation(-mapCoord.Position) * Matrix3Helpers.CreateRotation(-worldRot);
        var shuttleToView = Matrix3x2.CreateScale(new Vector2(MinimapScale, -MinimapScale)) * Matrix3x2.CreateTranslation(MidPointVector);
        var rot = worldRot;

        // Draw shields
        DrawShields(handle, xform, worldToShuttle);

        // Frontier Corvax: north line drawing
        DrawNorthLine(handle, worldRot);

        // Mono
        switch (_azimuthMode)
        {
            case RadarAzimuthMode.Edge:
                DrawAzimuthScale(handle, worldRot);
                break;
            case RadarAzimuthMode.Ring:
                DrawAzimuthRing(handle, worldRot);
                break;
        }

        if (worldRot != Angle.Zero)
        {
            DrawCompassOverlay(handle, coordEntRot);
        }

        // Draw our grid in detail
        // Lua mod start
        EntityUid? ourGridIdNullable = xform.GridUid;
        EntityUid ourGridId = default;
        if (ourGridIdNullable != null)
        {
            ourGridId = ourGridIdNullable.Value;
            if (EntManager.TryGetComponent<MapGridComponent>(ourGridId, out var ourGrid) && fixturesQuery.HasComponent(ourGridId))
            {
                var ourGridToWorld = _transform.GetWorldMatrix(ourGridId);
                var ourGridToShuttle = Matrix3x2.Multiply(ourGridToWorld, worldToShuttle);
                var ourGridToView = ourGridToShuttle * shuttleToView;
                var color = _shuttles.GetIFFColor(ourGridId, self: true);
                var fill = color; // Lua
                var edge = color; // Lua
                var alpha = 0.01f; // Lua
                ModifyGridPalette(ref fill, ref edge, ref alpha, ourGridId, self: true); // Lua
                DrawGrid(handle, ourGridToView, (ourGridId, ourGrid), fill, edge, alpha); // Lua
                DrawDocks(handle, ourGridId, ourGridToView);
            }
        }
        // Lua mod end
        if (ShowRadarPositionMarker) // Lua
        {
            const float radarVertRadius = 2f;
            var radarPosVerts = new Vector2[]
            {
                ScalePosition(new Vector2(0f, -radarVertRadius)),
                ScalePosition(new Vector2(radarVertRadius / 2f, 0f)),
                ScalePosition(new Vector2(0f, radarVertRadius)),
                ScalePosition(new Vector2(radarVertRadius / -2f, 0f)),
            };

            handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, radarPosVerts, Color.Lime);
        }

        var viewBounds = new Box2Rotated(new Box2(-WorldRange, -WorldRange, WorldRange, WorldRange).Translated(mapPos.Position), rot, mapPos.Position);
        var viewAABB = viewBounds.CalcBoundingBox();

        _grids.Clear();
        _mapManager.FindGridsIntersecting(xform.MapID, new Box2(mapPos.Position - MaxRadarRangeVector, mapPos.Position + MaxRadarRangeVector), ref _grids, approx: true, includeMap: false);

        // Frontier - collect blip location data outside foreach - more changes ahead
        var blipDataList = new List<BlipData>();

        // Draw other grids... differently
        foreach (var grid in _grids)
        {
            var gUid = grid.Owner;
            if ((ourGridIdNullable != null && gUid == ourGridId) || !fixturesQuery.HasComponent(gUid)) // Lua Decrypt mod
                continue;

            var gridBody = bodyQuery.GetComponent(gUid);
            EntManager.TryGetComponent<IFFComponent>(gUid, out var iff);

            if (!_shuttles.CanDraw(gUid, gridBody, iff))
                continue;

            var flags = iff?.Flags ?? IFFFlags.None; // Lua mod
            var hideLabel = (flags & IFFFlags.HideLabel) != 0x0; // Lua mod
            var blipOnly = false; // no detection system: always allow outline
            var gridCenterMap = _transform.ToMapCoordinates(new EntityCoordinates(gUid, gridBody.LocalCenter)).Position;
            var worldDist = Vector2.Distance(gridCenterMap, mapPos.Position);
            var beyondRadar = worldDist > CornerRadarRange;
            if (MaximumIFFDistance >= 0.0f && worldDist > MaximumIFFDistance) continue;

            Matrix3x2 curGridToWorld = default;
            Matrix3x2 curGridToView = default;
            var needGeometry = !beyondRadar && !blipOnly;
            if (needGeometry)
            {
                curGridToWorld = _transform.GetWorldMatrix(gUid);
                curGridToView = curGridToWorld * worldToShuttle * shuttleToView;
            }

            var labelColor = _shuttles.GetIFFColor(grid, self: false, iff);
            var coordColor = new Color(labelColor.R * 0.8f, labelColor.G * 0.8f, labelColor.B * 0.8f, 0.5f);

            // Others default:
            // Color.FromHex("#FFC000FF")
            // Hostile default: Color.Firebrick
            string? labelName;
            if (hideLabel) { labelName = null; }
            else
            {
                labelName = _shuttles.GetIFFLabel(grid, self: false, iff) ?? Loc.GetString("shuttle-console-unknown");
            }

            var isPlayerShuttle = iff != null && (iff.Flags & IFFFlags.IsPlayerShuttle) != 0x0;
            var shouldDrawIFF = ShowIFF && labelName != null;
            if (IFFFilter != null)
            {
                shouldDrawIFF &= IFFFilter(gUid, grid.Comp, iff, labelName);
            }
            if (isPlayerShuttle)
            {
                shouldDrawIFF &= ShowIFFShuttles;
            }

            //var mapCenter = curGridToWorld. * gridBody.LocalCenter;
            //shouldDrawIFF = NfCheckShouldDrawIffRangeCondition(shouldDrawIFF, mapCenter, curGridToWorld); // Frontier code
            // Frontier: range checks
            var gridMapPos = gridCenterMap;
            shouldDrawIFF = NFCheckShouldDrawIffRangeCondition(shouldDrawIFF, gridMapPos - mapPos.Position);
            // End Frontier

            // Frontier: IFF drawing functions
            // The actual position in the UI. We offset the matrix position to render it off by half its width
            // plus by the offset.
            var uiPosition = Vector2.Transform(gridCenterMap, worldToShuttle * shuttleToView) / UIScale;

            // Confines the UI position within the viewport.
            var uiXCentre = (int)Width / 2;
            var uiYCentre = (int)Height / 2;
            var uiXOffset = uiPosition.X - uiXCentre;
            var uiYOffset = uiPosition.Y - uiYCentre;
            var uiDistance = (int)Math.Sqrt(Math.Pow(uiXOffset, 2) + Math.Pow(uiYOffset, 2));
            var uiX = uiXCentre * uiXOffset / uiDistance;
            var uiY = uiYCentre * uiYOffset / uiDistance;

            var isOutsideRadarCircle = uiDistance > Math.Abs(uiX) && uiDistance > Math.Abs(uiY);
            if (isOutsideRadarCircle)
            {
                // 0.95f for offsetting the icons slightly away from edge of radar so it doesnt clip.
                uiX = uiXCentre * uiXOffset / uiDistance * 0.95f;
                uiY = uiYCentre * uiYOffset / uiDistance * 0.95f;
                uiPosition = new Vector2(
                    x: uiX + uiXCentre,
                    y: uiY + uiYCentre
                );
            }

            var allowBlip = !hideLabel;

            const float FullScaleDistance = 512f;
            const float MinDistanceScale = 0.35f;
            var maxScaleRange = MathF.Max(WorldMaxRange, FullScaleDistance + 1f);
            var distanceScale = worldDist <= FullScaleDistance
                ? 1f
                : MathF.Max(MinDistanceScale, 1f - (worldDist - FullScaleDistance) / (maxScaleRange - FullScaleDistance) * (1f - MinDistanceScale));

            if (ShowIFF && allowBlip)
            {
                NFAddBlipToList(blipDataList, isOutsideRadarCircle, uiPosition, uiXCentre, uiYCentre, labelColor, 1f);
            }
            if (shouldDrawIFF)
            {
                var scaledMousePosition = GetScaledMouseUiPosition();
                var isMouseOver = Vector2.Distance(scaledMousePosition, uiPosition * UIScale) < 30f;

                // Distant stations that are not player controlled ships
                var isDistantPOI = iff != null || (iff == null || (iff.Flags & IFFFlags.IsPlayerShuttle) == 0x0);

                var distance = worldDist;

                if (!isOutsideRadarCircle || isDistantPOI || isMouseOver)
                {
                    // Shows decimal when distance is < 50m, otherwise pointless to show it.
                    var displayedDistance = distance < 50f ? $"{distance:0.0}" : distance < 1000 ? $"{distance:0}" : $"{distance / 1000:0.0}k";
                    var labelText = Loc.GetString("shuttle-console-iff-label", ("name", labelName)!, ("distance", displayedDistance));

                    var coordsText = $"({gridMapPos.X:0.0}, {gridMapPos.Y:0.0})";

                    // Calculate unscaled offsets.
                    var mainLabel = labelText;
                    var dimScale = 0.9f * distanceScale;
                    var labelDimensions = handle.GetDimensions(Font, mainLabel, dimScale);
                    var blipSize = RadarBlipSize * 0.7f * distanceScale;
                    var labelOffset = new Vector2()
                    {
                        X = uiPosition.X > Width / 2f
                            ? -labelDimensions.X - blipSize // right align the text to left of the blip
                            : blipSize, // left align the text to the right of the blip
                        Y = -labelDimensions.Y / 2f
                    };
                    var displayColor = labelColor;

                    var textScale = UIScale * 0.9f * distanceScale;
                    handle.DrawString(Font, (uiPosition + labelOffset) * UIScale, mainLabel, textScale, displayColor);

                    if (isMouseOver && !HideCoords)
                    {
                        var coordDimensions = handle.GetDimensions(Font, coordsText, 0.7f);
                        var coordOffset = new Vector2()
                        {
                            X = uiPosition.X > Width / 2f
                                ? -coordDimensions.X - blipSize / 0.7f // right align the text to left of the blip (0.7 needed for scale)
                                : blipSize, // left align the text to the right of the blip
                            Y = labelOffset.Y + handle.GetDimensions(Font, mainLabel, 1f).Y + 5
                        };
                        handle.DrawString(Font, (uiPosition + coordOffset) * UIScale, coordsText, 0.7f * UIScale, coordColor);
                    }
                }

            }

            // Frontier Don't skip drawing blips if they're out of range.
            NFDrawBlips(handle, blipDataList);

            // Detailed view
            var gridAABB = curGridToWorld.TransformBox(grid.Comp.LocalAABB);

            // Skip drawing if it's out of range.
            if (beyondRadar || !gridAABB.Intersects(viewAABB)) continue;

            // Mono
            if (!blipOnly)
            {
                var fill = labelColor; // Lua
                var edge = labelColor; // Lua
                var alpha = 0.01f; // Lua
                ModifyGridPalette(ref fill, ref edge, ref alpha, gUid, self: false); // Lua
                DrawGrid(handle, curGridToView, grid, fill, edge, alpha); // Lua
                DrawDocks(handle, gUid, curGridToView);
            }
        }

        // Frontier: draw target
        if (!HideTarget && Target is { } target)
        {
            var targetEntity = EntManager.GetEntity(TargetEntity);

            string targetName;
            if (EntManager.TryGetComponent<MetaDataComponent>(targetEntity, out var targetMeta))
                targetName = targetMeta.EntityName;
            else
                targetName = Loc.GetString("shuttle-console-target-name");

            var curGridToView = Matrix3Helpers.CreateTranslation(target) * worldToShuttle * shuttleToView;

            var labelColor = TargetColor;
            var coordColor = new Color(TargetColor.R * 0.8f, TargetColor.G * 0.8f, TargetColor.B * 0.8f, 0.5f);

            //var gridCentre = Vector2.Transform(gridBody.LocalCenter, curGridToView);
            //gridCentre.Y = -gridCentre.Y;

            // Frontier: IFF drawing functions
            // The actual position in the UI. We offset the matrix position to render it off by half its width
            // plus by the offset.
            //var uiPosition = ScalePosition(gridCentre) / UIScale;
            var uiPosition = Vector2.Transform(Vector2.Zero, curGridToView) / UIScale;

            // Confines the UI position within the viewport.
            var uiXCentre = (int)Width / 2;
            var uiYCentre = (int)Height / 2;
            var uiXOffset = uiPosition.X - uiXCentre;
            var uiYOffset = uiPosition.Y - uiYCentre;
            var uiDistance = (int)Math.Sqrt(Math.Pow(uiXOffset, 2) + Math.Pow(uiYOffset, 2));
            var uiX = uiXCentre * uiXOffset / uiDistance;
            var uiY = uiYCentre * uiYOffset / uiDistance;

            var isOutsideRadarCircle = uiDistance > Math.Abs(uiX) && uiDistance > Math.Abs(uiY);
            if (isOutsideRadarCircle)
            {
                // 0.95f for offsetting the icons slightly away from edge of radar so it doesnt clip.
                uiX = uiXCentre * uiXOffset / uiDistance * 0.95f;
                uiY = uiYCentre * uiYOffset / uiDistance * 0.95f;
                uiPosition = new Vector2(
                    x: uiX + uiXCentre,
                    y: uiY + uiYCentre
                );
            }

            var scaledMousePosition = GetScaledMouseUiPosition();
            var isMouseOver = Vector2.Distance(scaledMousePosition, uiPosition * UIScale) < 30f;

            var distance = Vector2.Distance(target, mapPos.Position);

            // Shows decimal when distance is < 50m, otherwise pointless to show it.
            var displayedDistance = distance < 50f ? $"{distance:0.0}" : distance < 1000 ? $"{distance:0}" : $"{distance / 1000:0.0}k";
            var labelText = Loc.GetString("shuttle-console-iff-label", ("name", targetName)!, ("distance", displayedDistance));

            var coordsText = $"({target.X:0.0}, {target.Y:0.0})";

            // Calculate unscaled offsets.
            var labelDimensions = handle.GetDimensions(Font, labelText, 1f);
            var blipSize = RadarBlipSize * 0.7f;
            var labelOffset = new Vector2()
            {
                X = uiPosition.X > Width / 2f
                    ? -labelDimensions.X - blipSize // right align the text to left of the blip
                    : blipSize, // left align the text to the right of the blip
                Y = -labelDimensions.Y / 2f
            };

            handle.DrawString(Font, (uiPosition + labelOffset) * UIScale, labelText, UIScale, labelColor);
            if (isMouseOver && !HideCoords)
            {
                var coordDimensions = handle.GetDimensions(Font, coordsText, 0.7f);
                var coordOffset = new Vector2()
                {
                    X = uiPosition.X > Width / 2f
                        ? -coordDimensions.X - blipSize / 0.7f // right align the text to left of the blip (0.7 needed for scale)
                        : blipSize, // left align the text to the right of the blip
                    Y = coordDimensions.Y / 2
                };
                handle.DrawString(Font, (uiPosition + coordOffset) * UIScale, coordsText, 0.7f * UIScale, coordColor);
            }

            NFAddBlipToList(blipDataList, isOutsideRadarCircle, uiPosition, uiXCentre, uiYCentre, labelColor, 1f, targetEntity ?? default); // Frontier code
            // End Frontier: IFF drawing functions
        }

        // Draw all blips on the map at this point.
        NFDrawBlips(handle, blipDataList);
        // End Frontier: draw target

        // If we've set the controlling console, and it's on a different grid
        // to the shuttle itself, then draw an additional marker to help the
        // player determine where they are relative to the shuttle.
        if (_consoleEntity != null && xformQuery.TryGetComponent(_consoleEntity, out var consoleXform))
        {
            if (consoleXform.ParentUid != _coordinates.Value.EntityId)
            {
                var consolePositionWorld = _transform.GetWorldPosition((EntityUid)_consoleEntity);
                var p = Vector2.Transform(consolePositionWorld, worldToShuttle * shuttleToView);
                handle.DrawCircle(p, 5, Color.ToSrgb(Color.Cyan), true);
            }
        }

        #region Mono
        // Draw radar line
        // First, figure out which angle to draw.
        var updateRatio = _updateAccumulator / RadarUpdateInterval;

        Angle angle = updateRatio * Math.Tau;
        var origin = ScalePosition(-new Vector2(Offset.X, -Offset.Y));
        handle.DrawLine(origin, origin + angle.ToVec() * ScaledMinimapRadius * 1.42f, Color.Red.WithAlpha(0.1f));

        // Get blips
        var rawBlips = _blips.GetCurrentBlips();
        const int MaxBlipsDraw = 320;
        var blipStride = Math.Max(1, rawBlips.Count / MaxBlipsDraw);

        // Prepare view bounds for culling
        var monoViewBounds = new Box2(-3f, -3f, Size.X + 3f, Size.Y + 3f);

        // Draw blips using the same grid-relative transformation approach as docks
        foreach (var blip in rawBlips)
        {
            var blipMap = _transform.ToMapCoordinates(blip.Position);
            if (blipMap.MapId != xform.MapID) continue;
            if (Vector2.Distance(blipMap.Position, mapPos.Position) > CornerRadarRange) continue;
            var blipPosInView = Vector2.Transform(blipMap.Position, worldToShuttle * shuttleToView);

            // Check if this blip is within view bounds before drawing
            if (monoViewBounds.Contains(blipPosInView))
            {
                var drawScale = blip.Scale;
                var drawColor = blip.Color;
                var drawShape = blip.Shape;

                DrawBlipShape(handle, blipPosInView, drawScale * 3f, drawColor.WithAlpha(0.8f), drawShape);
            }
        }

        // Draw hitscan lines from the radar blips system
        var hitscanLines = _blips.GetHitscanLines();
        foreach (var line in hitscanLines)
        {
            var startPosInView = Vector2.Transform(line.Start, worldToShuttle * shuttleToView);
            var endPosInView = Vector2.Transform(line.End, worldToShuttle * shuttleToView);

            // Only draw lines if at least one endpoint is within view
            if (monoViewBounds.Contains(startPosInView) || monoViewBounds.Contains(endPosInView))
            {
                // Draw the line with the specified thickness and color
                handle.DrawLine(startPosInView, endPosInView, line.Color);

                // For thicker lines, draw multiple lines side by side
                if (line.Thickness > 1.0f)
                {
                    // Calculate perpendicular vector for thickness
                    var dir = (endPosInView - startPosInView).Normalized();
                    var perpendicular = new Vector2(-dir.Y, dir.X) * 0.5f;

                    // Draw additional lines for thickness
                    for (float i = 1; i <= line.Thickness; i += 1.0f)
                    {
                        var offset = perpendicular * i;
                        handle.DrawLine(startPosInView + offset, endPosInView + offset, line.Color);
                        handle.DrawLine(startPosInView - offset, endPosInView - offset, line.Color);
                    }
                }
            }
        }

        DrawWeaponLines(handle); // Lua

        ClearShader(handle);
        #endregion
    }

    private void DrawDocks(DrawingHandleScreen handle, EntityUid uid, Matrix3x2 gridToView)
    {
        if (!ShowDocks)
            return;

        const float DockScale = 0.6f;
        const float HighlightDockScale = 1.0f; // Lua
        var nent = EntManager.GetNetEntity(uid);

        const float sqrt2 = 1.41421356f;
        const float dockRadius = HighlightDockScale * sqrt2;
        // Worst-case bounds used to cull a dock:
        Box2 viewBounds = new Box2(
            -dockRadius * UIScale,
            -dockRadius * UIScale,
            (Size.X + dockRadius) * UIScale,
            (Size.Y + dockRadius) * UIScale);

        if (_docks.TryGetValue(nent, out var docks))
        {
            foreach (var state in docks)
            {
                var position = state.Coordinates.Position;

                var positionInView = Vector2.Transform(position, gridToView);
                if (!viewBounds.Contains(positionInView))
                {
                    continue;
                }

                //var color = Color.ToSrgb(Color.Magenta); // Frontier
                var color = Color.ToSrgb(state.HighlightedRadarColor); // Frontier
                GetDockColorOverride(ref color, state); // Lua

                var scale = DockScale; // Lua
                if (HighlightDockPort.HasValue && state.Entity == HighlightDockPort.Value) scale = HighlightDockScale;
                var verts = new[]
                {
                    Vector2.Transform(position + new Vector2(-scale, -scale), gridToView),
                    Vector2.Transform(position + new Vector2(scale, -scale), gridToView),
                    Vector2.Transform(position + new Vector2(scale, scale), gridToView),
                    Vector2.Transform(position + new Vector2(-scale, scale), gridToView),
                };

                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, verts, color.WithAlpha(0.8f));
                handle.DrawPrimitives(DrawPrimitiveTopology.LineStrip, verts, color);
            }

            // Frontier: draw dock labels (done last to appear on top of all docks, still fights with other grids)
            var labeled = new HashSet<string>();
            foreach (var state in docks)
            {
                if (state.LabelName == null || labeled.Contains(state.LabelName))
                    continue;

                var position = state.Coordinates.Position;
                var uiPosition = Vector2.Transform(position, gridToView);

                if (!viewBounds.Contains(uiPosition))
                    continue;

                labeled.Add(state.LabelName);
                var labelDimensions = handle.GetDimensions(Font, state.LabelName, 0.9f);
                handle.DrawString(Font, (uiPosition / UIScale - labelDimensions / 2) * UIScale, state.LabelName, UIScale * 0.9f, _dockLabelColor);
            }
            // End Frontier
        }
    }
    partial void GetDockColorOverride(ref Color color, DockingPortState state); // Lua
    protected Vector2 InverseScalePosition(Vector2 value)
    {
        // Account for UI scaling: value is unscaled, so adjust by UIScale
        var scaledValue = value * UIScale;
        return (scaledValue - MidPointVector) / MinimapScale;
    }

    // Mono
    protected EntityCoordinates GetMouseEntityCoordinates(Vector2 relativePosition)
    {
        if (_coordinates is not { } cord || _rotation is not { } rot)
            return EntityCoordinates.Invalid;

        // multiply by UIScale because UI is Very Intelligent and doesn't scale mouse position for whatever reason
        var screenRelativeWorldPos = InverseMapPosition(relativePosition * UIScale);
        var relativeWorldPos = rot.RotateVec(screenRelativeWorldPos);
        var coordEntRot = _transform.GetWorldRotation(cord.EntityId);
        var coords = cord.Offset((-coordEntRot).RotateVec(relativeWorldPos));
        return coords;
    }

    public class BlipData
    {
        public bool IsOutsideRadarCircle { get; set; }
        public Vector2 UiPosition { get; set; }
        public Vector2 VectorToPosition { get; set; }
        public Color Color { get; set; }
        public float Scale { get; set; } = 1f;
    }

    private const int RadarBlipSize = 15;
    private const int RadarFontSize = 8;

    private void DrawShields(DrawingHandleScreen handle, TransformComponent consoleXform, Matrix3x2 matrix)
    {
        var shields = EntManager.AllEntityQueryEnumerator<ShipShieldVisualsComponent, FixturesComponent, TransformComponent>();
        var consoleWorldPos = _transform.GetWorldPosition(consoleXform);
        while (shields.MoveNext(out var uid, out var visuals, out var fixtures, out var xform))
        {
            if (!EntManager.TryGetComponent<TransformComponent>(xform.GridUid, out var parentXform))
                continue;

            if (xform.MapID != consoleXform.MapID)
                continue;

            // Don't draw shields when in FTL
            if (EntManager.HasComponent<FTLComponent>(parentXform.Owner)) continue;
            var shieldWorldPos = _transform.GetWorldPosition(parentXform);
            if (Vector2.Distance(shieldWorldPos, consoleWorldPos) > CornerRadarRange) continue;

            var shieldFixture = fixtures.Fixtures.TryGetValue("shield", out var fixture) ? fixture : null;

            if (shieldFixture == null || shieldFixture.Shape is not ChainShape)
                continue;

            ChainShape chain = (ChainShape)shieldFixture.Shape;

            var count = chain.Count;
            var verticies = chain.Vertices;

            const int MaxSegments = 1000;
            var stride = Math.Max(1, count / MaxSegments);

            var center = xform.LocalPosition;

            for (int i = 1; i < count; i++)
            {
                var v1 = Vector2.Add(center, verticies[i - 1]);
                v1 = Vector2.Transform(v1, parentXform.WorldMatrix); // transform to world matrix
                v1 = Vector2.Transform(v1, matrix); // get back to local matrix for drawing
                v1.Y = -v1.Y;
                v1 = ScalePosition(v1);
                var nextIndex = Math.Min(i, count - 1);
                var v2 = Vector2.Add(center, verticies[nextIndex]);
                v2 = Vector2.Transform(v2, parentXform.WorldMatrix);
                v2 = Vector2.Transform(v2, matrix);
                v2.Y = -v2.Y;
                v2 = ScalePosition(v2);
                handle.DrawLine(v1, v2, visuals.ShieldColor);
            }
        }
    }
}
