using System.Buffers;
using System.Numerics;
using Content.Client.Shuttles.Systems;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.UI.MapObjects;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Collections;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ShuttleMapControl : BaseShuttleControl
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IInputManager _inputs = default!;
    [Dependency] private readonly IEntityManager _entManager = default!; // Frontier

    private readonly SharedMapSystem _mapSystem;
    private readonly ShuttleSystem _shuttles;
    private readonly SharedTransformSystem _xformSystem;
    private readonly Content.Client.Parallax.ParallaxSystem _parallaxSystem;

    protected override bool Draggable => true;
    protected override bool AllowResize => true; // Lua
    protected override bool ScaleWithControlSize => true; // Lua
    protected override Vector2 MidPointVector => new Vector2(PixelWidth * 0.5f, PixelHeight * 0.5f);

    public bool ShowBeacons = true;
    public MapId ViewingMap = MapId.Nullspace;

    private EntityUid? _shuttleEntity;

    private readonly Font _font;

    private readonly EntityQuery<PhysicsComponent> _physicsQuery;

    /// <summary>
    /// Toggles FTL mode on. This shows a pre-vis for FTLing a grid.
    /// </summary>
    public bool FtlMode;

    /// <summary>
    /// Shows only the FTL range circle without cursor targeting elements.
    /// </summary>
    public bool ShowFTLRangeOnly;

    public bool ShowFTLRange = true;

    public bool NoFTLRange = false;

    private Angle _ftlAngle;

    /// <summary>
    /// Are we currently in FTL.
    /// </summary>
    public bool InFtl;

    /// <summary>
    /// Raised when a request to FTL to a particular spot is raised.
    /// </summary>
    public event Action<MapCoordinates, Angle>? RequestFTL;

    public event Action<NetEntity, Angle>? RequestBeaconFTL;

    /// <summary>
    /// Lua: Toggles marker-placement mode on. Clicking the map raises MarkPlaced with the clicked map position.
    /// </summary>
    public bool MarkMode;

    /// <summary>
    /// Lua: Raised when the player clicks the map while in marker-placement mode.
    /// </summary>
    public event Action<MapCoordinates>? MarkPlaced;

    /// <summary>
    /// Set every draw to determine the beacons that are clickable for mouse events
    /// </summary>
    private List<IMapObject> _beacons = new();

    // Per frame data to avoid re-allocating
    private readonly List<IMapObject> _mapObjects = new();
    private readonly Dictionary<Color, List<Vector2>> _verts = new();
    private readonly Dictionary<Color, List<Vector2>> _edges = new();
    private readonly Dictionary<Color, List<(Vector2, string)>> _strings = new();
    private readonly List<(Vector2 Position, string Icon, Color Color)> _glyphs = new();
    private readonly List<ShuttleExclusionObject> _viewportExclusions = new();

    public ShuttleMapControl() : base(256f, 6144f, 6144f) // Lua 512f, 512f<6144f, 6144f
    {
        RobustXamlLoader.Load(this);
        _mapSystem = EntManager.System<SharedMapSystem>();
        _shuttles = EntManager.System<ShuttleSystem>();
        _xformSystem = EntManager.System<SharedTransformSystem>();
        _parallaxSystem = EntManager.System<Content.Client.Parallax.ParallaxSystem>();
        var cache = IoCManager.Resolve<IResourceCache>();

        _physicsQuery = EntManager.GetEntityQuery<PhysicsComponent>();

        _font = new VectorFont(cache.GetResource<FontResource>("/Fonts/NotoSans/NotoSans-Regular.ttf"), 9);
    }

    public void SetMap(MapId mapId, Vector2 offset, bool recentering = false)
    {
        ViewingMap = mapId;
        TargetOffset = offset;
        Recentering = recentering;
    }

    public void SetShuttle(EntityUid? entity)
    {
        _shuttleEntity = entity;
    }

    // Lua: normalized 0-1 zoom slider support
    public float RadarZoom => WorldMaxRange > WorldMinRange
        ? Math.Clamp((WorldRange - WorldMinRange) / (WorldMaxRange - WorldMinRange), 0f, 1f)
        : 0f;

    public void SetRadarZoom(float zoom)
    {
        zoom = Math.Clamp(zoom, 0f, 1f);
        ActualRadarRange = WorldMinRange + (WorldMaxRange - WorldMinRange) * zoom;
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        // Lua: marker-placement mode - click the map to place a target marker instead of FTL-ing there.
        if (MarkMode && ViewingMap != MapId.Nullspace && args.Function == EngineKeyFunctions.UIClick)
        {
            var mapCoords = new MapCoordinates(InverseMapPosition(args.RelativePixelPosition), ViewingMap);
            MarkPlaced?.Invoke(mapCoords);
            return;
        }

        if (FtlMode && ViewingMap != MapId.Nullspace)
        {
            if (args.Function == EngineKeyFunctions.UIClick)
            {
                var mapUid = _mapSystem.GetMapOrInvalid(ViewingMap);

                var beaconsOnly = EntManager.TryGetComponent(mapUid, out FTLDestinationComponent? destComp) &&
                                  destComp.BeaconsOnly;

                var mapTransform = Matrix3Helpers.CreateInverseTransform(Offset, Angle.Zero);

                if (beaconsOnly && TryGetBeacon(_beacons, mapTransform, args.RelativePixelPosition, PixelRect, out var foundBeacon, out _))
                {
                    RequestBeaconFTL?.Invoke(foundBeacon.Entity, _ftlAngle);
                }
                else
                {
                    // We'll send the "adjusted" position and server will adjust it back when relevant.
                    var mapCoords = new MapCoordinates(InverseMapPosition(args.RelativePixelPosition), ViewingMap);

                    if (!_physicsQuery.TryGetComponent(_shuttleEntity, out var shuttlePhysics) || !EntManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleTransform))
                        return;

                    var shuttleUid = _shuttleEntity.Value;

                    var shuttlePosition = Maps.GetGridPosition((shuttleUid, shuttlePhysics, shuttleTransform));
                    var targetPosition = mapCoords.Position;
                    var shuttleToTarget = targetPosition - shuttlePosition;

                    var range = _shuttles.GetFTLRange(shuttleUid);

                    // If the target position is outside of the shuttle's FTL range, then try to FTL as close as possible to save the player some hassle.
                    if (!NoFTLRange && shuttleToTarget.Length() > range)
                    {
                        mapCoords = new(shuttlePosition + shuttleToTarget.Normalized() * range, ViewingMap);
                    }

                    RequestFTL?.Invoke(mapCoords, _ftlAngle);
                }
            }
        }

        base.KeyBindUp(args);
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        // Scroll handles FTL rotation if you're in FTL mode.
        if (FtlMode)
        {
            _ftlAngle -= Angle.FromDegrees(15f) * args.Delta.Y; // Mono Edit: Subtract instead of add to preserve clockwise rotation when scrolling up. (positive angles are actually counter-clockwise)
            _ftlAngle = _ftlAngle.Reduced();
            return;
        }

        base.MouseWheel(args);
    }

    private void DrawParallax(DrawingHandleScreen handle)
    {
        if (ViewingMap == MapId.Nullspace)
            return;

        var position = ScalePosition(new Vector2(-Offset.X, Offset.Y));
        var curTime = _timing.RealTime;

        foreach (var layer in _parallaxSystem.GetParallaxLayers(ViewingMap))
        {
            var tex = layer.Texture;
            var config = layer.Config;

            // Size of the texture in world units, scaled down to fit the minimap.
            var size = tex.Size * config.Scale * MinimapScale;

            if (size.X <= 0f || size.Y <= 0f)
                continue;

            var botLeft = new Vector2(0f, 0f);
            var topRight = botLeft + PixelSize;

            if (!config.Tiled)
            {
                var origin = (botLeft + topRight) / 2 - size / 2 + config.ControlHomePosition * MinimapScale;
                handle.DrawTextureRect(tex, new UIBox2(origin, origin + size));
                continue;
            }

            var scrolled = config.Scrolling * (float)curTime.TotalSeconds * MinimapScale;

            // A slowness of 1 anchors the layer to the centre of the screen, while a slowness of 0 anchors it to the world.
            var originBL = position * config.Slowness + scrolled;

            // Centre the image.
            originBL -= size / 2;

            // Remove offset so we can floor.
            var flooredBL = botLeft - originBL;

            // Floor to background size.
            flooredBL = (flooredBL / size).Floored() * size;

            // Re-offset.
            flooredBL += originBL;

            for (var x = flooredBL.X; x < topRight.X; x += size.X)
            {
                for (var y = flooredBL.Y; y < topRight.Y; y += size.Y)
                {
                    handle.DrawTextureRect(tex, new UIBox2(x, y, x + size.X, y + size.Y));
                }
            }
        }
    }

    private void DrawTacticalMapBackground(DrawingHandleScreen handle, Matrix3x2 mapTransform, Box2 viewBox)
    {
        DrawParallax(handle);
        var bounds = UIBox2.FromDimensions(Vector2.Zero, PixelSize);
        handle.DrawRect(bounds, Color.FromHex("#243041").WithAlpha(0.7f), filled: false);

        DrawCoordinateGrid(handle, mapTransform, viewBox);
        DrawMapCompass(handle);
    }

    private void DrawCoordinateGrid(DrawingHandleScreen handle, Matrix3x2 mapTransform, Box2 viewBox)
    {
        if (MinimapScale <= 0f)
            return;

        var minorStep = GetNiceGridStep(46f / MinimapScale);
        var majorStep = minorStep * 4f;
        var minorColor = Color.FromHex("#7E8BA0").WithAlpha(0.08f);
        var majorColor = Color.FromHex("#8A96A8").WithAlpha(0.16f);
        var axisColor = Color.FromHex("#C5CEDB").WithAlpha(0.28f);
        var labelColor = Color.FromHex("#8A96A8").WithAlpha(0.7f);
        var labelShadow = Color.Black.WithAlpha(0.42f);

        DrawGridAxis(handle, mapTransform, viewBox.Left, viewBox.Right, viewBox.Bottom, viewBox.Top, minorStep, majorStep, minorColor, majorColor, axisColor, vertical: true);
        DrawGridAxis(handle, mapTransform, viewBox.Bottom, viewBox.Top, viewBox.Left, viewBox.Right, minorStep, majorStep, minorColor, majorColor, axisColor, vertical: false);
        DrawCoordinateLabels(handle, mapTransform, viewBox, majorStep, labelColor, labelShadow);
    }

    private static float GetNiceGridStep(float targetWorldStep)
    {
        targetWorldStep = MathF.Max(1f, targetWorldStep);
        var exponent = MathF.Floor(MathF.Log10(targetWorldStep));
        var magnitude = MathF.Pow(10f, exponent);
        var normalized = targetWorldStep / magnitude;
        var nice = normalized <= 1f ? 1f : normalized <= 2f ? 2f : normalized <= 5f ? 5f : 10f;
        return nice * magnitude;
    }

    private void DrawGridAxis(
        DrawingHandleScreen handle,
        Matrix3x2 mapTransform,
        float start,
        float end,
        float crossStart,
        float crossEnd,
        float minorStep,
        float majorStep,
        Color minorColor,
        Color majorColor,
        Color axisColor,
        bool vertical)
    {
        var first = MathF.Floor(start / minorStep) * minorStep;
        for (var value = first; value <= end; value += minorStep)
        {
            var color = MathF.Abs(value) < 0.01f
                ? axisColor
                : IsGridMajor(value, majorStep)
                    ? majorColor
                    : minorColor;

            var a = vertical ? new Vector2(value, crossStart) : new Vector2(crossStart, value);
            var b = vertical ? new Vector2(value, crossEnd) : new Vector2(crossEnd, value);
            handle.DrawLine(MapToScreen(a, mapTransform), MapToScreen(b, mapTransform), color);
        }
    }

    private void DrawCoordinateLabels(
        DrawingHandleScreen handle,
        Matrix3x2 mapTransform,
        Box2 viewBox,
        float majorStep,
        Color color,
        Color shadow)
    {
        var firstX = MathF.Floor(viewBox.Left / majorStep) * majorStep;
        for (var x = firstX; x <= viewBox.Right; x += majorStep)
        {
            var pos = MapToScreen(new Vector2(x, viewBox.Top), mapTransform) + new Vector2(4f, 5f);
            DrawSoftMapText(handle, x.ToString("0"), pos, 0.72f, color, shadow);
        }

        var firstY = MathF.Floor(viewBox.Bottom / majorStep) * majorStep;
        for (var y = firstY; y <= viewBox.Top; y += majorStep)
        {
            var pos = MapToScreen(new Vector2(viewBox.Left, y), mapTransform) + new Vector2(6f, -10f);
            DrawSoftMapText(handle, y.ToString("0"), pos, 0.72f, color, shadow);
        }
    }

    private static bool IsGridMajor(float value, float majorStep)
        => MathF.Abs(value / majorStep - MathF.Round(value / majorStep)) < 0.02f;

    private Vector2 MapToScreen(Vector2 worldPosition, Matrix3x2 mapTransform)
    {
        var adjusted = Vector2.Transform(worldPosition, mapTransform);
        return ScalePosition(adjusted with { Y = -adjusted.Y });
    }

    private void DrawMapCompass(DrawingHandleScreen handle)
    {
        var center = new Vector2(PixelWidth - 44f, 44f);
        const float radius = 24f;
        var ringColor = Color.FromHex("#8A96A8").WithAlpha(0.2f);
        var northColor = Color.FromHex("#F0C674").WithAlpha(0.86f);
        var eastColor = Color.FromHex("#7E8BA0").WithAlpha(0.82f);
        var southColor = Color.FromHex("#F0C674").WithAlpha(0.6f);
        var westColor = Color.FromHex("#7E8BA0").WithAlpha(0.58f);
        var headingColor = Color.FromHex("#5EC8E8").WithAlpha(0.9f);

        handle.DrawCircle(center, radius, ringColor, false);
        handle.DrawCircle(center, 2.5f, ringColor.WithAlpha(0.8f), true);
        DrawMapCompassNeedle(handle, center, new Vector2(0f, -1f), radius, "N", northColor);
        DrawMapCompassNeedle(handle, center, new Vector2(1f, 0f), radius * 0.82f, "E", eastColor);
        DrawMapCompassNeedle(handle, center, new Vector2(0f, 1f), radius * 0.82f, "S", southColor);
        DrawMapCompassNeedle(handle, center, new Vector2(-1f, 0f), radius * 0.82f, "W", westColor);
        if (_shuttleEntity is { } shuttle && EntManager.EntityExists(shuttle))
        {
            var heading = _xformSystem.GetWorldRotation(shuttle);
            var direction = GetMapCompassDirection(heading);
            DrawMapArrowLine(handle, center - direction * 7f, center + direction * (radius * 0.62f), headingColor, 7f);
        }
    }

    private static Vector2 GetMapCompassDirection(Angle heading)
    {
        var radians = (float) heading.Theta + MathF.PI / 2f;
        return new Vector2(MathF.Cos(radians), -MathF.Sin(radians));
    }

    private void DrawMapCompassNeedle(DrawingHandleScreen handle, Vector2 center, Vector2 direction, float radius, string label, Color color)
    {
        var tip = center + direction * radius;
        var tail = center - direction * (radius * 0.35f);
        DrawMapArrowLine(handle, tail, tip, color.WithAlpha(0.64f), 6f);

        var labelSize = handle.GetDimensions(_font, label, 0.85f);
        var labelPos = tip + direction * 6f - labelSize * 0.5f;
        DrawSoftMapText(handle, label, labelPos, 0.85f, color, Color.Black.WithAlpha(0.46f));
    }

    private static void DrawMapArrowLine(DrawingHandleScreen handle, Vector2 start, Vector2 end, Color color, float headLength)
    {
        var direction = end - start;
        if (direction.LengthSquared() <= 0.001f)
            return;

        direction = Vector2.Normalize(direction);
        var side = new Vector2(-direction.Y, direction.X);
        handle.DrawLine(start, end, color);
        handle.DrawLine(end, end - direction * headLength + side * (headLength * 0.45f), color);
        handle.DrawLine(end, end - direction * headLength - side * (headLength * 0.45f), color);
    }

    private void DrawSoftMapText(DrawingHandleScreen handle, string text, Vector2 position, float scale, Color color, Color shadow)
    {
        handle.DrawString(_font, position + new Vector2(1f, 1f), text, scale, shadow);
        handle.DrawString(_font, position, text, scale, color);
    }

    private Box2 GetVisibleWorldBox()
    {
        var scale = MinimapScale;
        if (scale <= 0f)
            return Box2.CenteredAround(Offset, WorldRangeVector * 2f);

        var mid = MidPointVector;
        var minLocal = -mid;
        var maxLocal = new Vector2(PixelWidth, PixelHeight) - mid;
        var worldMinX = Offset.X + minLocal.X / scale;
        var worldMaxX = Offset.X + maxLocal.X / scale;
        var yA = Offset.Y - minLocal.Y / scale;
        var yB = Offset.Y - maxLocal.Y / scale;
        return new Box2(
            MathF.Min(worldMinX, worldMaxX),
            MathF.Min(yA, yB),
            MathF.Max(worldMinX, worldMaxX),
            MathF.Max(yA, yB));
    }

    /// <summary>
    /// Gets the map objects that intersect the viewport.
    /// </summary>
    /// <param name="mapObjects"></param>
    /// <returns></returns>
    private List<IMapObject> GetViewportMapObjects(Matrix3x2 matty, List<IMapObject> mapObjects)
    {
        var results = new List<IMapObject>();
        var enlargement = new Vector2i((int) (16 * UIScale), (int) (16 * UIScale));
        var viewBox = new UIBox2i(Vector2i.Zero - enlargement, PixelSize + enlargement);

        foreach (var mapObj in mapObjects)
        {
            // If it's a grid-map skip it.
            if (mapObj is GridMapObject gridObj && (EntManager.HasComponent<MapComponent>(gridObj.Entity) || !_entManager.EntityExists(gridObj.Entity))) // Frontier: add EntityExists
                continue;

            var mapCoords = _shuttles.GetMapCoordinates(mapObj);

            var relativePos = Vector2.Transform(mapCoords.Position, matty);
            relativePos = relativePos with { Y = -relativePos.Y };
            var uiPosition = ScalePosition(relativePos);

            if (!viewBox.Contains(uiPosition.Floored()))
                continue;

            results.Add(mapObj);
        }

        return results;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (ViewingMap == MapId.Nullspace)
            return;

        var mapObjects = _mapObjects;
        DrawRecenter();

        if (InFtl || mapObjects.Count == 0)
        {
            DrawBacking(handle);
            DrawNoSignal(handle);
            return;
        }

        var viewedMapUid = _mapSystem.GetMapOrInvalid(ViewingMap);
        var matty = Matrix3Helpers.CreateInverseTransform(Offset, Angle.Zero);
        var realTime = _timing.RealTime;
        var viewBox = GetVisibleWorldBox();
        DrawTacticalMapBackground(handle, matty, viewBox);
        var viewportObjects = GetViewportMapObjects(matty, mapObjects);
        _viewportExclusions.Clear();

        // Draw our FTL range + no FTL zones
        // Do it up here because we want this layered below most things.
        if ((FtlMode || ShowFTLRangeOnly) && ShowFTLRange)
        {
            if (EntManager.TryGetComponent<TransformComponent>(_shuttleEntity, out var shuttleXform))
            {
                var gridUid = _shuttleEntity.Value;
                var gridPhysics = _physicsQuery.GetComponent(gridUid);
                var (gridPos, gridRot) = _xformSystem.GetWorldPositionRotation(shuttleXform);
                gridPos = Maps.GetGridPosition((gridUid, gridPhysics), gridPos, gridRot);

                var gridRelativePos = Vector2.Transform(gridPos, matty);
                gridRelativePos = gridRelativePos with { Y = -gridRelativePos.Y };
                var gridUiPos = ScalePosition(gridRelativePos);

                var range = _shuttles.GetFTLRange(gridUid);
                range *= MinimapScale;
                handle.DrawCircle(gridUiPos, range, Color.Gold, filled: false);
            }
        }

        var exclusionColor = Color.Red;

        // Exclusions need a bumped range so we check all the ones on the map.
        foreach (var mapObj in mapObjects)
        {
            if (mapObj is not ShuttleExclusionObject exclusion)
                continue;

            // Check if it even intersects the viewport.
            var coords = EntManager.GetCoordinates(exclusion.Coordinates);
            var mapCoords = _xformSystem.ToMapCoordinates(coords);
            var enlargedBounds = viewBox.Enlarged(exclusion.Range);

            if (mapCoords.MapId != ViewingMap ||
                !enlargedBounds.Contains(mapCoords.Position))
            {
                continue;
            }
            _viewportExclusions.Add(exclusion);

            var adjustedPos = Vector2.Transform(mapCoords.Position, matty);
            var localPos = ScalePosition(adjustedPos with { Y = -adjustedPos.Y});
            handle.DrawCircle(localPos, exclusion.Range * MinimapScale, exclusionColor.WithAlpha(0.05f));
            handle.DrawCircle(localPos, exclusion.Range * MinimapScale, exclusionColor, filled: false);
        }
        _verts.Clear();
        _edges.Clear();
        _strings.Clear();
        _glyphs.Clear();

        // Add beacons if relevant.
        var beaconsOnly = _shuttles.IsBeaconMap(viewedMapUid);
        var controlLocalBounds = PixelRect;
        _beacons.Clear();

        if (ShowBeacons)
        {
            var beaconColor = Color.AliceBlue;

            foreach (var (beaconName, coords, mapO) in GetBeacons(viewportObjects, matty, controlLocalBounds))
            {
                var localPos = Vector2.Transform(coords.Position, matty);
                localPos = localPos with { Y = -localPos.Y };
                var beaconUiPos = ScalePosition(localPos);
                var mapObject = GetMapObject(localPos, Angle.Zero, scale: 0.75f, scalePosition: true);

                var displayColor = beaconColor;

                var existingVerts = _verts.GetOrNew(displayColor);
                var existingEdges = _edges.GetOrNew(displayColor);

                AddMapObject(existingEdges, existingVerts, mapObject);
                _beacons.Add(mapO);
                _glyphs.Add((beaconUiPos, "◎", displayColor));
            }
        }

        foreach (var mapObj in viewportObjects)
        {
            if (mapObj is not GridMapObject gridObj || !EntManager.TryGetComponent(gridObj.Entity, out MapGridComponent? mapGrid))
                continue;

            Entity<MapGridComponent> grid = (gridObj.Entity, mapGrid);
            EntManager.TryGetComponent(grid, out IFFComponent? iffComp);
            if (grid.Owner != _shuttleEntity && !_shuttles.CanDraw(grid.Owner, iffComp: iffComp))
                continue;

            var gridColor = _shuttles.GetIFFColor(grid, self: _shuttleEntity == grid.Owner, component: iffComp);

            var existingVerts = _verts.GetOrNew(gridColor);
            var existingEdges = _edges.GetOrNew(gridColor);

            var gridPhysics = _physicsQuery.GetComponent(grid.Owner);
            var (gridPos, gridRot) = _xformSystem.GetWorldPositionRotation(grid.Owner);
            gridPos = Maps.GetGridPosition((grid, gridPhysics), gridPos, gridRot);

            var gridRelativePos = Vector2.Transform(gridPos, matty);
            gridRelativePos = gridRelativePos with { Y = -gridRelativePos.Y };
            var gridUiPos = ScalePosition(gridRelativePos);

            var flags = iffComp?.Flags ?? IFFFlags.None;
            var hideLabel = (flags & IFFFlags.HideLabel) != 0x0;
            if (hideLabel)
            {
                var mapObject = GetMapObject(gridRelativePos, Angle.Zero, scalePosition: true);
                AddMapObject(existingEdges, existingVerts, mapObject);
                continue;
            }

            var iffText = _shuttles.GetIFFLabel(grid, self: _shuttleEntity == grid.Owner, component: iffComp);
            iffText ??= Loc.GetString("shuttle-console-unknown");

            if (string.IsNullOrEmpty(iffText))
                continue;

            var mapObj2 = GetMapObject(gridRelativePos, Angle.Zero, scalePosition: true); // Lua decrypt mod
            AddMapObject(existingEdges, existingVerts, mapObj2); // Lua decrypt mod
            var existingStrings = _strings.GetOrNew(gridColor);
            existingStrings.Add((gridUiPos, iffText));
        }

        // Batch the colors whoopie
        // really only affects forks with lots of grids.
        foreach (var (color, sendVerts) in _verts)
        {
            handle.DrawPrimitives(DrawPrimitiveTopology.TriangleList, sendVerts, color.WithAlpha(0.05f));
        }

        foreach (var (color, sendEdges) in _edges)
        {
            handle.DrawPrimitives(DrawPrimitiveTopology.LineList, sendEdges, color.WithAlpha(0.78f));
        }

        foreach (var (position, icon, color) in _glyphs)
        {
            var size = handle.GetDimensions(_font, icon, 0.92f);
            DrawSoftMapText(handle, icon, position - size * 0.5f, 0.92f, color.WithAlpha(0.96f), Color.Black.WithAlpha(0.55f));
        }

        foreach (var (color, sendStrings) in _strings)
        {
            var displayColor = Color.FromSrgb(color);

            foreach (var (gridUiPos, iffText) in sendStrings)
            {
                var lines = iffText.Split('\n');
                var mainLabel = lines[0];
                var mainTextWidth = handle.GetDimensions(_font, mainLabel, 1f);

                DrawSoftMapText(handle, mainLabel, gridUiPos + mainTextWidth with { X = -mainTextWidth.X / 2f, Y = mainTextWidth.Y * UIScale }, 1f, displayColor.WithAlpha(0.92f), Color.Black.WithAlpha(0.48f));

                if (lines.Length > 1)
                {
                    var companyLabel = lines[1];
                    var companyTextWidth = handle.GetDimensions(_font, companyLabel, 1f);
                    var companyLabelOffset = mainTextWidth with
                    {
                        X = -companyTextWidth.X / 2f,
                        Y = mainTextWidth.Y * 2 * UIScale
                    };

                    DrawSoftMapText(handle, companyLabel, gridUiPos + companyLabelOffset, 1f, displayColor.WithAlpha(0.78f), Color.Black.WithAlpha(0.42f));
                }
            }
        }

        var mousePos = _inputs.MouseScreenPosition;
        var mouseLocalPos = GetLocalPosition(mousePos);

        // Draw dotted line from our own shuttle entity to mouse.
        if (FtlMode && !ShowFTLRangeOnly)
        {
            if (mousePos.Window != WindowId.Invalid)
            {
                // If mouse inbounds then draw it.
                if (_shuttleEntity != null && controlLocalBounds.Contains(mouseLocalPos.Floored()) &&
                    EntManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform) &&
                    shuttleXform.MapID != MapId.Nullspace)
                {
                    // If it's a beacon only map then snap the mouse to a nearby spot.
                    ShuttleBeaconObject foundBeacon = default;

                    // Check for beacons around mouse and snap to that.
                    if (beaconsOnly && TryGetBeacon(viewportObjects, matty, mouseLocalPos, controlLocalBounds, out foundBeacon, out var foundLocalPos))
                    {
                        mouseLocalPos = foundLocalPos;
                    }

                    var grid = EntManager.GetComponent<MapGridComponent>(_shuttleEntity.Value);

                    var (gridPos, gridRot) = _xformSystem.GetWorldPositionRotation(shuttleXform);
                    gridPos = Maps.GetGridPosition(_shuttleEntity.Value, gridPos, gridRot);

                    // do NOT apply LocalCenter operation here because it will be adjusted in FTLFree.
                    var mouseMapPos = InverseMapPosition(mouseLocalPos);

                    var ftlFree = (!beaconsOnly || foundBeacon != default) &&
                                  _shuttles.FTLFree(_shuttleEntity.Value, new EntityCoordinates(viewedMapUid, mouseMapPos), _ftlAngle, _viewportExclusions)
                                  || NoFTLRange; // Mono

                    var color = ftlFree ? Color.LimeGreen : Color.Magenta;

                    var gridRelativePos = Vector2.Transform(gridPos, matty);
                    gridRelativePos = gridRelativePos with { Y = -gridRelativePos.Y };
                    var gridUiPos = ScalePosition(gridRelativePos);

                    // Draw FTL buffer around the mouse.
                    var ourFTLBuffer = _shuttles.GetFTLBufferRange(_shuttleEntity.Value, grid);
                    ourFTLBuffer *= MinimapScale;
                    handle.DrawCircle(mouseLocalPos, ourFTLBuffer, Color.Magenta.WithAlpha(0.01f));
                    handle.DrawCircle(mouseLocalPos, ourFTLBuffer, Color.Magenta, filled: false);

                    // Draw line from our shuttle to target
                    // Might need to clip the line if it's too far? But my brain wasn't working so F.
                    handle.DrawDottedLine(gridUiPos, mouseLocalPos, color, (float) realTime.TotalSeconds * 30f);

                    // Draw shuttle pre-vis
                    var mouseVerts = GetMapObject(mouseLocalPos, -_ftlAngle, scale: MinimapScale); // Mono Edit: UI controls and the map are in different coordinate orientations, so the angle has to be negated. (shuttle Y is UI control -Y)

                    handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, mouseVerts.Span, color.WithAlpha(0.05f));
                    handle.DrawPrimitives(DrawPrimitiveTopology.LineLoop, mouseVerts.Span, color);

                    // Draw a notch indicating direction.
                    var ftlLength = GetMapObjectRadius() + 16f;
                    var ftlEnd = mouseLocalPos + (-_ftlAngle).RotateVec(new Vector2(0f, -ftlLength)); // Mono Edit: UI controls and the map are in different coordinate orientations, so the angle has to be negated. (shuttle Y is UI control -Y)

                    handle.DrawLine(mouseLocalPos, ftlEnd, color);
                }
            }
        }

        // Draw the coordinates
        var mapOffset = MidPointVector;

        if (mousePos.Window != WindowId.Invalid &&
            controlLocalBounds.Contains(mouseLocalPos.Floored()))
        {
            mapOffset = mouseLocalPos;
        }

        mapOffset = InverseMapPosition(mapOffset);
        var coordsText = $"{mapOffset.X:0.0}, {mapOffset.Y:0.0}";

        DrawMapData(handle, coordsText, Color.White);
    }

    private void AddMapObject(List<Vector2> edges, List<Vector2> verts, ValueList<Vector2> mapObject)
    {
        var bottom = mapObject[0];
        var right = mapObject[1];
        var top = mapObject[2];
        var left = mapObject[3];

        // Diamond interior
        verts.Add(bottom);
        verts.Add(right);
        verts.Add(top);

        verts.Add(bottom);
        verts.Add(top);
        verts.Add(left);

        // Diamond edges
        edges.Add(bottom);
        edges.Add(right);
        edges.Add(right);
        edges.Add(top);
        edges.Add(top);
        edges.Add(left);
        edges.Add(left);
        edges.Add(bottom);
    }

    /// <summary>
    /// Returns the beacons that intersect the viewport.
    /// </summary>
    private IEnumerable<(string Beacon, MapCoordinates Coordinates, IMapObject MapObject)> GetBeacons(List<IMapObject> mapObjs, Matrix3x2 mapTransform, UIBox2i area)
    {
        foreach (var mapO in mapObjs)
        {
            if (mapO is not ShuttleBeaconObject beacon)
                continue;

            var beaconCoords = _xformSystem.ToMapCoordinates(EntManager.GetCoordinates(beacon.Coordinates));
            var position = Vector2.Transform(beaconCoords.Position, mapTransform);
            var localPos = ScalePosition(position with {Y = -position.Y});

            // If beacon not on screen then ignore it.
            if (!area.Contains(localPos.Floored()))
                continue;

            yield return (beacon.Name, beaconCoords, mapO);
        }
    }

    private float GetMapObjectRadius(float scale = 1f) => WorldRange / 40f * scale;

    private ValueList<Vector2> GetMapObject(Vector2 localPos, Angle angle, float scale = 1f, bool scalePosition = false)
    {
        // Constant size diamonds
        var diamondRadius = GetMapObjectRadius();

        var mapObj = new ValueList<Vector2>(4)
        {
            localPos + angle.RotateVec(new Vector2(0f, -2f * diamondRadius)) * scale,
            localPos + angle.RotateVec(new Vector2(diamondRadius, 0f)) * scale,
            localPos + angle.RotateVec(new Vector2(0f, 2f * diamondRadius)) * scale,
            localPos + angle.RotateVec(new Vector2(-diamondRadius, 0f)) * scale,
        };

        if (scalePosition)
        {
            for (var i = 0; i < mapObj.Count; i++)
            {
                mapObj[i] = ScalePosition(mapObj[i]);
            }
        }

        return mapObj;
    }

    private bool TryGetBeacon(IEnumerable<IMapObject> mapObjects, Matrix3x2 mapTransform, Vector2 mousePos, UIBox2i area, out ShuttleBeaconObject foundBeacon, out Vector2 foundLocalPos)
    {
        // In pixels
        const float BeaconSnapRange = 32f;
        float nearestValue = float.MaxValue;
        foundLocalPos = Vector2.Zero;
        foundBeacon = default;

        foreach (var mapObj in mapObjects)
        {
            if (mapObj is not ShuttleBeaconObject beaconObj)
                continue;

            var beaconCoords = _xformSystem.ToMapCoordinates(EntManager.GetCoordinates(beaconObj.Coordinates));

            if (beaconCoords.MapId != ViewingMap)
                continue;

            // Invalid beacon?
            if (!_shuttles.CanFTLBeacon(beaconObj.Coordinates))
                continue;

            var position = Vector2.Transform(beaconCoords.Position, mapTransform);
            var localPos = ScalePosition(position with {Y = -position.Y});

            // If beacon not on screen then ignore it.
            if (!area.Contains(localPos.Floored()))
                continue;

            var distance = (localPos - mousePos).Length();

            if (distance > BeaconSnapRange * UIScale ||
                distance > nearestValue)
            {
                continue;
            }

            foundLocalPos = localPos;
            nearestValue = distance;
            foundBeacon = beaconObj;
        }

        return foundBeacon != default;
    }

    /// <summary>
    /// Sets the map objects for the next draw.
    /// </summary>
    public void SetMapObjects(Dictionary<MapId, List<IMapObject>> mapObjects)
    {
        _mapObjects.Clear();

        if (mapObjects.TryGetValue(ViewingMap, out var obbies))
        {
            _mapObjects.AddRange(obbies);
        }
    }

    /// <summary>
    /// Draw the coordinate data with a custom color.
    /// </summary>
    private void DrawMapData(DrawingHandleScreen handle, string text, Color color)
    {
        var font = _font;
        var dimensions = handle.GetDimensions(font, text, 1f);
        var position = new Vector2(15f, PixelHeight - dimensions.Y - 15f);
        DrawSoftMapText(handle, text, position, 1f, color.WithAlpha(0.9f), Color.Black.WithAlpha(0.5f));
    }
}
