- type: entity
  id: DeployedStationBase
  parent: BaseStation
  categories: [ HideSpawnMenu ]
  components:
  - type: Transform
  - type: StationOrderDatabase
  - type: StationDevelopment
  - type: ExtraShuttleInformation

- type: gameMap
  id: DeployedStation
  mapName: 'Deployed Station'
  mapPath: /Maps/_Horizon/CustomStation/station.yml
  minPlayers: 0
  stations:
    DeployedStation:
      stationProto: DeployedStationBase
      components:
      - type: StationNameSetup
        mapNameTemplate: 'Deployed Station {1}'
        nameGenerator:
          !type:NanotrasenNameGenerator
          prefixCreator: 'DS'
