- type: entity
  id: ComputerStationControl
  parent: BaseComputer
  name: station control console
  description: Lets you rename this station. Further station management features are not yet operational.
  components:
  - type: StationControlConsole
  - type: ActivatableUI
    key: enum.StationControlConsoleUiKey.Key
  - type: UserInterface
    interfaces:
      enum.StationControlConsoleUiKey.Key:
        type: StationControlConsoleBoundUserInterface

- type: entity
  id: ComputerStationTask
  parent: BaseComputer
  name: station task console
  description: Lets you browse the station's active orders and summon/recall a cargo capsule to deliver them.
  components:
  - type: StationTaskConsole
  - type: ActivatableUI
    key: enum.StationTaskConsoleUiKey.Key
  - type: UserInterface
    interfaces:
      enum.StationTaskConsoleUiKey.Key:
        type: StationTaskConsoleBoundUserInterface
