- type: entity
  id: ComputerStationControlPlaceholder
  parent: BaseComputer
  name: station control console
  description: A control interface for managing this station. Not yet operational.
  components:
  - type: StationControlConsole

- type: entity
  id: ComputerStationTaskPlaceholder
  parent: BaseComputer
  name: station task console
  description: An interface for managing station tasks. Not yet operational.
  components:
  - type: StationTaskConsole
