using System.Linq;
using Content.Shared._Horizon.StationDeployment.Prototypes;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Horizon.StationDeployment;

[GenerateTypedNameReferences]
public sealed partial class StationOrderCardControl : Control
{
    public StationOrderCardControl(StationOrderPrototype order, IPrototypeManager prototypeManager, SpriteSystem spriteSys)
    {
        RobustXamlLoader.Load(this);

        var discipline = prototypeManager.Index<TechDisciplinePrototype>(order.Category);
        Background.ModulateSelfOverride = discipline.Color;

        OrderTexture.Texture = order.Sprite != null ? spriteSys.Frame0(order.Sprite) : spriteSys.Frame0(discipline.Icon);

        DescriptionLabel.SetMessage(order.Description == string.Empty ? Loc.GetString(discipline.Name) : Loc.GetString(order.Description));

        var requirements = string.Join(", ", order.Entries.Select(e => Loc.GetString("station-task-console-item-line", ("amount", e.Amount), ("item", Loc.GetString(e.Name)))));
        RequirementsLabel.SetMessage(requirements);
    }
}
