using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon.StationDeployment;

[GenerateTypedNameReferences]
public sealed partial class StationControlConsoleWindow : FancyWindow
{
    public Action<string>? OnNameChange;
    public Action<int>? OnWithdraw;
    public Action<int>? OnDeposit;
    public Action<string>? OnIffColorChange;

    private int _withdrawAmount;
    private bool _bankEnabled;

    public StationControlConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        NameSelectorSet.OnPressed += _ => OnNameChange?.Invoke(NameSelector.Text);

        WithdrawEdit.OnTextChanged += args =>
        {
            _withdrawAmount = int.TryParse(args.Text, out var amount) ? amount : 0;
            UpdateButtons();
        };
        WithdrawButton.OnPressed += _ => OnWithdraw?.Invoke(_withdrawAmount);

        // The server clamps this to however much cash is actually inserted.
        DepositButton.OnPressed += _ => OnDeposit?.Invoke(int.MaxValue);

        IffColorEdit.OnTextChanged += args => UpdateIffColorPreview(args.Text);
        IffColorSetButton.OnPressed += _ => OnIffColorChange?.Invoke(IffColorEdit.Text);
    }

    public void UpdateState(string name, int balance, bool bankEnabled, int deposit, string iffColorHex)
    {
        NameSelector.Text = name;

        _bankEnabled = bankEnabled;
        BalanceLabel.Text = bankEnabled ? BankSystemExtensions.ToSpesoString(balance) : Loc.GetString("bank-atm-menu-no-bank");
        DepositLabel.Text = deposit >= 0 ? BankSystemExtensions.ToSpesoString(deposit) : Loc.GetString("bank-atm-menu-cash-error");

        if (!IffColorEdit.HasKeyboardFocus())
        {
            IffColorEdit.Text = iffColorHex;
            UpdateIffColorPreview(iffColorHex);
        }

        UpdateButtons();
    }

    private void UpdateIffColorPreview(string hex)
    {
        if (Color.TryFromHex(hex) is { } color)
            IffColorPreview.PanelOverride = new StyleBoxFlat(color);
    }

    private void UpdateButtons()
    {
        WithdrawButton.Disabled = !_bankEnabled || _withdrawAmount <= 0;
        DepositButton.Disabled = !_bankEnabled;
    }
}
