using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Horizon.StationDeployment;
using Content.Shared._Horizon.StationDeployment.Prototypes;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Horizon.StationDeployment;

[GenerateTypedNameReferences]
public sealed partial class StationTaskConsoleWindow : FancyWindow
{
    public Action? OnSummonPressed;
    public Action? OnRecallPressed;
    public Action<string>? OnOrderCancelPressed;

    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private readonly SpriteSystem _sprite;

    public StationTaskConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();

        SummonButton.OnPressed += _ => OnSummonPressed?.Invoke();
        RecallButton.OnPressed += _ => OnRecallPressed?.Invoke();
    }

    public void UpdateState(StationTaskConsoleBuiState state)
    {
        CapsuleStatusLabel.SetMessage(Loc.GetString(state switch
        {
            { CapsulePresent: false } => "station-task-console-capsule-none",
            { CapsuleDocked: false } => "station-task-console-capsule-en-route",
            _ => "station-task-console-capsule-docked",
        }));

        OrdersCountLabel.SetMessage(Loc.GetString("station-task-console-orders-count", ("count", state.Orders.Count)));

        RecallButton.Disabled = !state.CapsuleDocked;

        CategoryLevelsContainer.Children.Clear();
        foreach (var (categoryId, progress) in state.Levels.OrderBy(kv => kv.Key.Id))
        {
            // Skip categories whose discipline prototype isn't available client-side, rather than crashing the whole BUI.
            if (!_prototype.TryIndex<TechDisciplinePrototype>(categoryId, out var discipline))
                continue;

            var texture = new TextureRect
            {
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center,
                Texture = _sprite.Frame0(discipline.Icon),
            };
            var label = new RichTextLabel();
            label.SetMessage(Loc.GetString("station-task-console-level-info",
                ("level", progress.Level), ("progress", progress.Progress), ("needed", progress.OrdersPerLevel)));

            CategoryLevelsContainer.AddChild(new BoxContainer
            {
                Children =
                {
                    texture,
                    label,
                    new Control { MinWidth = 10 },
                },
            });
        }

        OrdersContainer.Children.Clear();
        if (state.Orders.Count == 0)
        {
            OrdersContainer.AddChild(new Label { Text = Loc.GetString("station-task-console-no-orders"), HorizontalAlignment = HAlignment.Center });
        }

        foreach (var order in state.Orders)
        {
            if (!_prototype.TryIndex(order.Order, out var prototype))
                continue;

            var card = new StationOrderCardControl(prototype, _prototype, _sprite);
            card.OnCancelPressed += () => OnOrderCancelPressed?.Invoke(order.Id);
            OrdersContainer.AddChild(card);
        }
    }
}
