using System.Linq;
using Content.Shared._Horizon.StationDeployment.Prototypes;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Horizon.StationDeployment;

[GenerateTypedNameReferences]
public sealed partial class StationOrderCardControl : Control
{
    public StationOrderCardControl(StationOrderPrototype order, IPrototypeManager prototypeManager, SpriteSystem spriteSys)
    {
        RobustXamlLoader.Load(this);

        // The discipline prototype might not be available client-side - degrade gracefully instead of crashing the card.
        prototypeManager.TryIndex<TechDisciplinePrototype>(order.Category, out var discipline);

        if (discipline != null)
        {
            Background.ModulateSelfOverride = discipline.Color;
            CategoryTexture.Texture = spriteSys.Frame0(discipline.Icon);
        }

        if (order.Sprite != null)
            OrderTexture.Texture = spriteSys.Frame0(order.Sprite);
        else if (discipline != null)
            OrderTexture.Texture = spriteSys.Frame0(discipline.Icon);

        TitleLabel.Text = order.Description != string.Empty
            ? Loc.GetString(order.Description)
            : discipline != null ? Loc.GetString(discipline.Name) : string.Empty;

        var requirements = string.Join(", ", order.Entries.Select(e => Loc.GetString("station-task-console-item-line", ("amount", e.Amount), ("item", Loc.GetString(e.Name)))));
        RequirementsLabel.SetMessage(requirements);
    }
}
