using Content.Client.UserInterface.Controls;
using Content.Shared._Horizon.StationDeployment;
using Content.Shared._Horizon.StationDeployment.Prototypes;
using Content.Shared._NF.Bank;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._Horizon.StationDeployment;

[GenerateTypedNameReferences]
public sealed partial class StationControlConsoleWindow : FancyWindow
{
    public Action<string>? OnNameChange;
    public Action<int>? OnWithdraw;
    public Action<int>? OnDeposit;
    public Action<string>? OnIffColorChange;
    public Action<ProtoId<StationUpgradePurchasePrototype>>? OnPurchaseUpgrade;

    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private int _withdrawAmount;
    private bool _bankEnabled;

    public StationControlConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        NameSelectorSet.OnPressed += _ => OnNameChange?.Invoke(NameSelector.Text);

        WithdrawEdit.OnTextChanged += args =>
        {
            _withdrawAmount = int.TryParse(args.Text, out var amount) ? amount : 0;
            UpdateButtons();
        };
        WithdrawButton.OnPressed += _ => OnWithdraw?.Invoke(_withdrawAmount);

        // The server clamps this to however much cash is actually inserted.
        DepositButton.OnPressed += _ => OnDeposit?.Invoke(int.MaxValue);

        IffColorEdit.OnTextChanged += args => UpdateIffColorPreview(args.Text);
        IffColorSetButton.OnPressed += _ => OnIffColorChange?.Invoke(IffColorEdit.Text);
    }

    public void UpdateState(string name, int balance, bool bankEnabled, int deposit, string iffColorHex, List<StationUpgradePurchaseUiEntry> upgrades)
    {
        NameSelector.Text = name;

        _bankEnabled = bankEnabled;
        BalanceLabel.Text = bankEnabled ? BankSystemExtensions.ToSpesoString(balance) : Loc.GetString("bank-atm-menu-no-bank");
        DepositLabel.Text = deposit >= 0 ? BankSystemExtensions.ToSpesoString(deposit) : Loc.GetString("bank-atm-menu-cash-error");

        if (!IffColorEdit.HasKeyboardFocus())
        {
            IffColorEdit.Text = iffColorHex;
            UpdateIffColorPreview(iffColorHex);
        }

        UpdateButtons();
        UpdateUpgrades(upgrades);
    }

    private void UpdateUpgrades(List<StationUpgradePurchaseUiEntry> upgrades)
    {
        UpgradesContainer.Children.Clear();

        foreach (var upgrade in upgrades)
        {
            if (!_prototype.TryIndex(upgrade.Id, out var proto))
                continue;

            var categoryName = _prototype.TryIndex<TechDisciplinePrototype>(proto.Category, out var discipline)
                ? Loc.GetString(discipline.Name)
                : proto.Category.Id;

            var nameLabel = new Label { Text = Loc.GetString(proto.Name), StyleClasses = { "LabelKeyText" }, HorizontalExpand = true };
            var reqLabel = new RichTextLabel();
            reqLabel.SetMessage(Loc.GetString("station-control-console-upgrade-level-req",
                ("category", categoryName), ("level", upgrade.RequiredLevel)));
            var priceLabel = new Label { Text = Loc.GetString("station-control-console-upgrade-price", ("price", upgrade.Price)), StyleClasses = { "LabelSubText" } };
            var limitLabel = new Label
            {
                Text = upgrade.Limit is { } limitText
                    ? Loc.GetString("station-control-console-upgrade-limit", ("purchased", upgrade.Purchased), ("limit", limitText))
                    : string.Empty,
                StyleClasses = { "LabelSubText" },
            };

            var limitReached = upgrade.Limit is { } limit && upgrade.Purchased >= limit;
            var buyButton = new Button
            {
                Text = Loc.GetString("station-control-console-upgrade-buy-button"),
                Disabled = !upgrade.Unlocked || !upgrade.Affordable || limitReached,
            };
            buyButton.OnPressed += _ => OnPurchaseUpgrade?.Invoke(upgrade.Id);

            UpgradesContainer.AddChild(new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(4),
                Children =
                {
                    nameLabel,
                    reqLabel,
                    new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Horizontal,
                        Children = { priceLabel, limitLabel, new Control { HorizontalExpand = true }, buyButton },
                    },
                },
            });
        }
    }

    private void UpdateIffColorPreview(string hex)
    {
        if (Color.TryFromHex(hex) is { } color)
            IffColorPreview.PanelOverride = new StyleBoxFlat(color);
    }

    private void UpdateButtons()
    {
        WithdrawButton.Disabled = !_bankEnabled || _withdrawAmount <= 0;
        DepositButton.Disabled = !_bankEnabled;
    }
}
