using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon.StationDeployment;

[GenerateTypedNameReferences]
public sealed partial class StationControlConsoleWindow : FancyWindow
{
    public Action<string>? OnNameChange;

    public StationControlConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        NameSelectorSet.OnPressed += _ =>
        {
            OnNameChange?.Invoke(NameSelector.Text);
        };
    }

    public void UpdateState(string name)
    {
        NameSelector.Text = name;
    }
}
